const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
test('live screen loop awards drops, buys, equips and saves progress',async()=>{
 const gradient={addColorStop(){}},ctx=new Proxy({createLinearGradient:()=>gradient,createRadialGradient:()=>gradient},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)}),els={},storage=new Map(),errors=[];let raf;
 const element=id=>els[id]??=(id==='battle'?{getContext:()=>ctx}:{dataset:{},classList:{toggle(){}},textContent:'',innerHTML:''});
 const box={console:{error:e=>errors.push(e.message)},document:{getElementById:element,querySelectorAll:()=>[],addEventListener(){}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},requestAnimationFrame:fn=>raf=fn,GameCore:{loot:require('./balanced_loot.cjs'),combat:require('./live_combat.cjs'),shop:require('./town_shop.cjs'),enemies:require('./enemies.cjs').enemies},SwordArt:{load:async()=>({}),combo:()=>()=>{},other:()=>()=>{}}};
 box.window=box;box.GearCompare=require('../compare.js');vm.createContext(box);vm.runInContext(fs.readFileSync(path.join(__dirname,'../elements.js'),'utf8'),box);vm.runInContext(fs.readFileSync(path.join(__dirname,'../game.js'),'utf8'),box);await new Promise(setImmediate);assert.equal(els.start.disabled,false);for(const id of ['triple','thrust','sweep','leap','flame','frost','thunder','basic']){box.checkId=id;assert.ok(vm.runInContext('poseTime(checkId,.9999)<motionProfile(checkId).source.slice(0,-1).reduce((a,b)=>a+b,0)',box),'no return-to-ready frame: '+id);}els.start.onclick();
 let engagedFrames=0;for(let t=0;t<240000;t+=100){raf(t);if(vm.runInContext('running&&!town&&fightTime>.3',box)){assert.ok(vm.runInContext('heroAdvance>=140',box),'stay in melee range between skills');engagedFrames++;}if(vm.runInContext('town',box))els.start.onclick();}
 assert.ok(engagedFrames>100);const result=vm.runInContext('({wins:s.wins,kills:s.kills,bag:s.bag.length,level:s.level,gold:s.gold})',box);assert.equal(errors.length,0,errors.join('\n'));assert.ok(result.wins>10);assert.ok(result.kills>=result.wins);assert.ok(result.bag>3,'natural drops appear');assert.ok(result.level>1);
 els.town.onclick();for(let t=240000;t<280000&&!vm.runInContext('town',box);t+=100)raf(t);assert.equal(vm.runInContext('town',box),true);
 els.normalOnly.onclick();assert.equal(vm.runInContext('player().actions.length',box),0);els.normalOnly.onclick();assert.equal(vm.runInContext('player().actions.length',box),5);
 const oldStats=vm.runInContext('({free:unspent(),knowledge:player().stats.知識})',box);assert.ok(oldStats.free>0);els.allocation.onclick({target:{dataset:{stat:'知識'}}});assert.equal(vm.runInContext('unspent()',box),oldStats.free-1);assert.equal(vm.runInContext('player().stats.知識',box),oldStats.knowledge+1);assert.equal(vm.runInContext('motionProfile("basic")===motionProfiles.basic',box),true);
 const before=vm.runInContext('({gold:s.gold,potions:s.state.potions})',box);els.buy.onclick();const after=vm.runInContext('({gold:s.gold,potions:s.state.potions})',box);assert.equal(before.gold-after.gold,(after.potions-before.potions)*10);
 const id=vm.runInContext('s.bag.find(x=>!s.gear.includes(x.id)&&x.req<=s.level)?.id',box);if(id!==undefined){const predicted=vm.runInContext('GearCompare.compare(loot,s.level,s.gear.map(id=>s.bag.find(x=>x.id===id)),s.enhance,s.bag.find(x=>x.id==='+id+'),s.allocation).after',box);els.equipment.onclick({target:{closest:()=>({dataset:{equip:String(id)}})}});assert.equal(vm.runInContext('s.gear.includes('+id+')',box),true);assert.equal(vm.runInContext('player().atk',box),predicted.atk);assert.equal(vm.runInContext('player().hp',box),predicted.hp);}
 els.save.onclick();const saved=JSON.parse([...storage.values()][0]);assert.equal(saved.kills,vm.runInContext('s.kills',box));assert.ok(saved.wins>=result.wins);assert.deepEqual(saved.queue,['triple','thrust','sweep','leap','heal_potion']);console.log('240 simulated seconds:',result);els.elementPreset.onclick();assert.deepEqual(JSON.parse(vm.runInContext('JSON.stringify(s.queue)',box)),['flame','frost','thunder','heal_potion','thrust']);els.start.onclick();for(let t=280000;t<300000;t+=100)raf(t);assert.equal(errors.length,0,errors.join('\n'));assert.ok(vm.runInContext('specs[s.queue[0]].element',box));
});
