const test=require('node:test'),assert=require('node:assert/strict');
const old=require(require('node:fs').existsSync(__dirname+'/../../restored/revised_combat.cjs')?'../../restored/revised_combat.cjs':'../../revised_combat.cjs'),live=require('./live_combat.cjs'),{player,item}=require('./balanced_loot.cjs'),{enemies}=require('./enemies.cjs');
const gear=level=>['weapon','armor','charm'].map(slot=>({slot,baseLevel:level,quality:1,ops:[]}));
function run(p,seed=1,state={}){const g=live.stream({player:p,enemies:[{hp:10000,atk:0,interval:2}],state,seed,maxSeconds:2});let x,events=[];do{x=g.next();events.push(...(x.done?x.value.view:x.value).events);}while(!x.done);return{result:x.value,events};}
test('100 legacy battles preserve exact numerical outcomes',()=>{for(const lv of [1,10,100,500,1000])for(let seed=1;seed<=20;seed++){const p=player(lv,gear(lv)),args={player:p,enemies:enemies(lv,false,3),seed};const a=old.battle(args),b=live.battle(args);delete b.view;delete b.state.cursor;assert.deepEqual(b,a);}});
test('triple hits three separate times and preserves total physical multiplier',()=>{const p={hp:100,atk:30,cp:100,hit:1,absoluteHit:true,ordered:true,actions:[{id:'triple',mult:3,cast:1.31,cooldown:10,hitFractions:[265/1310,500/1310,930/1310]}]};const {events}=run(p);const hits=events.filter(e=>e.id==='triple'&&e.type==='hit');assert.equal(hits.length,3);assert.deepEqual(hits.map(e=>Math.round(e.time*1000)),[265,500,930]);assert.equal(hits.reduce((n,e)=>n+e.damage,0),90);});
test('ordered actions rotate and cursor survives encounter boundaries',()=>{const p={hp:100,atk:1,cp:100,ordered:true,actions:['a','b','c'].map(id=>({id,cast:.2,cooldown:0}))};const {events}=run(p);assert.deepEqual(events.filter(e=>e.type==='cast').slice(0,6).map(e=>e.id),['a','b','c','a','b','c']);const v=run(p,1,{cursor:2});assert.equal(v.events[0].id,'c');});
test('unusable potion is skipped, low HP potion heals gradually',()=>{const p={hp:100,cp:100,atk:1,ordered:true,actions:[{id:'potion',type:'potion',cast:.5,cooldown:15,healRatio:.3,hpBelow:.4},{id:'sword',cast:1,cost:0}]};assert.equal(run(p,1,{hp:100,potions:2}).events[0].id,'sword');const v=run(p,1,{hp:30,potions:2});assert.equal(v.events[0].id,'potion');assert.equal(v.result.state.potions,1);assert.ok(v.result.hp>30&&v.result.hp<60);assert.ok(v.result.state.hots.length);});
test('killing strike completes its recovery without extra idle delay',()=>{const p={hp:100,cp:0,atk:1000,absoluteHit:true,ordered:true,actions:[{id:'hit',cast:1,hitFractions:[.4]}]};const b=live.battle({player:p,enemies:[{hp:10,atk:0}],seed:1});assert.equal(b.win,true);assert.equal(b.seconds,1);});
