const test=require('node:test'),assert=require('node:assert/strict'),S=require('../skills.js'),{stream,battle}=require('./live_combat.cjs');
const enemy={hp:10000,atk:100,interval:1,hit:1,def:100};
function player(actions,extra={}){return {hp:1000,cp:100,atk:100,hit:1,absoluteHit:true,ordered:true,skillRules:true,training:{},actions,...extra};}
function action(id,extra={}){return {...S.active[id],id,reduction:.5,cpRestore:24,...extra};}
function collect(p,state={},foes=[enemy],maxSeconds=3){const g=stream({player:p,enemies:foes,state,maxSeconds,seed:42}),events=[];let n;do{n=g.next();if(!n.done)events.push(...n.value.events);}while(!n.done);events.push(...n.value.view.events);return {events,result:n.value};}
test('20 skills; migration, investment budget, cap and respec preserve progress',()=>{assert.equal(Object.keys(S.all).length,20);const s={level:1,queue:['triple','thrust','sweep','leap','heal_potion'],gold:123,bag:[1]};S.migrate(s);assert.equal(s.queue.length,5);for(let i=0;i<10;i++)assert.ok(S.train(s,i<9?'guard':'focus'));assert.equal(S.train(s,'wave'),false);S.reset(s);assert.equal(S.spent(s),0);assert.equal(s.gold,123);assert.deepEqual(s.bag,[1]);assert.equal(s.training.triple,1);assert.equal(s.training.guard,0);});
test('guard reduces incoming damage and survives battle state',()=>{const a=collect(player([action('guard')]),{hp:500}),b=collect(player([]),{hp:500});assert.ok(a.result.hp>b.result.hp);assert.ok(a.result.state.guardUntil>0);assert.equal(a.events.filter(e=>e.type==='hit'&&e.id==='guard').length,0);});
test('counter responds once, never spontaneously, and does not recursively proc',()=>{const a=collect(player([action('counter')]));assert.equal(a.events.filter(e=>e.type==='hit'&&e.id==='counter').length,1);assert.equal(collect(player([action('counter')]),{},[{...enemy,interval:99}]).events.filter(e=>e.id==='counter'&&e.type==='hit').length,0);});
test('focus restores CP only at completion; full CP skips it',()=>{const a=collect(player([action('focus')]),{cp:0},[{...enemy,atk:0}],1.21);assert.equal(a.result.cp,24);assert.equal(a.events.find(e=>e.type==='cp').time,1.2);assert.equal(collect(player([action('focus')])).events.some(e=>e.id==='focus'),false);});
test('wave hits two targets; break applies resistance-aware defense reduction',()=>{const a=collect(player([action('wave')]),{},[enemy,enemy,enemy],.7);assert.equal(new Set(a.events.filter(e=>e.type==='hit').map(e=>e.target)).size,2);const b=collect(player([action('break')]),{},[enemy],.5);assert.ok(b.result.view.foes[0].statuses.armorBreak>0);});
test('all six passives change their intended mechanics',()=>{const base={level:50,queue:['triple','wave','flame','counter','guard']};S.migrate(base);for(const id of Object.keys(S.all))base.training[id]=5;base.queue=['triple','wave','flame','counter','guard'];const raw=()=>({skills:[{id:'burst',mult:3.2}],cpBonus:0});const q=S.apply(raw(),base,S.active);assert.ok(q.cpBonus>0);assert.ok(q.actions.find(x=>x.id==='triple').hitBonus>0);assert.equal(q.actions.find(x=>x.id==='wave').targets,3);assert.ok(q.actions.find(x=>x.id==='guard').reduction>.25);for(const id of ['triple','flame'])assert.ok(q.actions.find(x=>x.id===id).mult>S.active[id].mult);});
test('both transformation links consume once, expire after use',()=>{for(const [id,link] of [['break','assault'],['counter','riposte']]){const p=player([action(id)],{training:{[link]:5}}),g=stream({player:p,enemies:[enemy],maxSeconds:5,seed:42});let triggered=false,events=[],n;do{n=g.next();if(!n.done){events.push(...n.value.events);if(!triggered&&n.value.events.some(e=>e.id===id&&e.type==='hit')){p.requestedForm='warrior';triggered=true;}}}while(!n.done);events.push(...n.value.view.events);assert.ok(events.some(e=>e.type==='form'&&e.form==='warrior'));assert.ok(events.some(e=>e.id==='warrior_heavy'&&e.type==='hit'));if(link==='assault')assert.ok(events.find(e=>e.id==='warrior_heavy'&&e.type==='hit').damage>140);else assert.ok(n.value.cp>50);assert.equal(n.value.state.linkDamage,1);assert.equal(n.value.state.linkDiscount,0);}});
test('separate potion does not occupy or move skill slots',()=>{const p=player([action('thrust')],{autoPotion:{id:'heal_potion',type:'potion',hpBelow:.4,healRatio:.3,cast:.5,cooldown:15}});const a=collect(p,{hp:200,potions:2});assert.equal(a.result.potionsUsed,1);assert.ok(a.events.some(e=>e.id==='thrust'));assert.equal(p.actions.length,1);});
