(()=>{'use strict';
const $=s=>document.querySelector(s),SAVE='skill-forge-v1';
const SKILLS={triple:{name:'三連斬',icon:'参',cost:12,power:1.65,cd:2.4,fx:'slash',hits:3},thrust:{name:'貫通突き',icon:'突',cost:9,power:1.45,cd:1.8,fx:'thrust',hits:1},sweep:{name:'低空薙ぎ',icon:'薙',cost:14,power:1.25,cd:3.2,fx:'sweep',hits:1,all:true},leap:{name:'飛込み斬',icon:'飛',cost:18,power:2.2,cd:4.4,fx:'slash',hits:1},potion:{name:'回復薬',icon:'薬',cost:0,power:0,cd:5.5,potion:true}};
const OP_POOL=[['str','力',1,12,100],['agi','敏捷',1,12,100],['vit','健康',1,12,100],['wis','知恵',1,12,92],['int','知識',1,12,92],['cha','威厳',1,12,90],['luck','運',1,10,78],['minAtk','最低攻撃',1,9,82],['maxAtk','最大攻撃',2,14,78],['def','防御',2,16,85],['hp','最大HP',4,30,66],['cp','最大CP',2,14,62],['accuracy','命中率',1,5,45],['evade','回避率',1,5,40],['crit','致命打率',1,4,24],['resist','全異常抵抗',1,5,22],['atkPct','攻撃力',2,8,15,'%'],['hpPct','最大HP',2,7,12,'%'],['speed','攻撃速度',1,4,4,'%']];
const BASES=['欠けた剣','青銅の剣','鉄の長剣','風切りの剣','白銀の剣','黒曜の剣'];
const defaultState=()=>({level:1,xp:0,xpNeed:24,gold:0,potions:3,wave:1,kills:0,points:0,stats:{str:10,agi:10,vit:10,wis:10,int:10,cha:10,luck:10},queue:['triple','thrust','sweep','potion','leap'],inventory:[],weapon:null});
let s=load(),battle,paused=false,speed=1,selected=-1,last=performance.now(),timers={};
function load(){try{return Object.assign(defaultState(),JSON.parse(localStorage.getItem(SAVE))||{})}catch{return defaultState()}}
function save(){localStorage.setItem(SAVE,JSON.stringify(s))}
function derived(){const o={str:0,agi:0,vit:0,hp:0,hpPct:0,atkPct:0,minAtk:0,maxAtk:0,cp:0,speed:0};if(s.weapon)s.weapon.ops.forEach(x=>o[x.key]=(o[x.key]||0)+x.value);const str=s.stats.str+o.str,vit=s.stats.vit+o.vit;return{maxHp:(130+vit*7+o.hp)*(1+o.hpPct/100),maxCp:42+s.stats.cha*2+o.cp,atk:(12+str*1.5+(o.minAtk+o.maxAtk)/2)*(1+o.atkPct/100),regen:1.1+vit*.035,cpRegen:3+s.stats.wis*.04,delay:1/(1+o.speed/100)}}
function makeBattle(){const d=derived(),count=1+Math.min(2,Math.floor((s.wave-1)%6/2));battle={hp:d.maxHp,cp:d.maxCp,index:0,wait:.35,enemies:Array.from({length:count},(_,i)=>{const lv=Math.max(1,Math.floor(s.level*.8+s.wave*.45)),elite=s.wave%8===0&&i===count-1,hp=45+lv*18;return{id:i,hp:hp*(elite?2.2:1),max:hp*(elite?2.2:1),lv,elite}})};renderEnemies();updateUI()}
function weightedOp(){let total=OP_POOL.reduce((a,x)=>a+x[4],0),r=Math.random()*total;for(const x of OP_POOL){r-=x[4];if(r<=0){const rank=Math.min(10,1+Math.floor(-Math.log(Math.max(.0001,Math.random()))*1.35)),v=Math.max(x[2],Math.round((x[2]+Math.random()*(x[3]-x[2]))*(.65+rank*.12)));return{key:x[0],name:x[1],rank,value:v,suffix:x[5]||''}}}return weightedOp()}
function drop(){const slots=Math.random()<.09?3:Math.random()<.4?2:1,ops=[];while(ops.length<slots){const o=weightedOp();if(!ops.some(x=>x.key===o.key))ops.push(o)}const req=Math.max(1,Math.round(s.level*.55+ops.reduce((a,o,i)=>a+o.rank*[.7,1,1.25][i],0))),tier=Math.min(BASES.length-1,Math.floor(s.level/18)),item={id:Date.now()+Math.random(),name:BASES[tier],level:s.level,req,ops,rarity:slots===3?'epic':slots===2?'rare':'magic'};s.inventory.unshift(item);if(s.inventory.length>80)s.inventory.length=80;toast('DROP  '+item.name+'  '+slots+'OP')}
function attack(skill){const d=derived(),alive=battle.enemies.filter(e=>e.hp>0);if(!alive.length)return;const targets=skill.all?alive:[alive[0]];$('#fighter').classList.remove('attack');void $('#fighter').offsetWidth;$('#fighter').classList.add('attack');$('#effect').className='effect '+skill.fx;setTimeout(()=>$('#effect').className='effect',360/speed);targets.forEach((e,ti)=>{for(let h=0;h<(skill.hits||1);h++)setTimeout(()=>{if(e.hp<=0)return;let crit=Math.random()<.06+s.stats.agi*.001,damage=Math.round(d.atk*skill.power/(skill.hits||1)*(.9+Math.random()*.2)*(crit?2:1));e.hp=Math.max(0,e.hp-damage);float(damage,e.id,crit?'crit':'');hitEnemy(e.id);updateEnemy(e);if(e.hp<=0)kill(e)},(h*105+ti*45)/speed)});$('#action').textContent=skill.name}
function usePotion(){if(s.potions<1||battle.hp>derived().maxHp*.72)return false;s.potions--;const heal=Math.round(derived().maxHp*.42);battle.hp=Math.min(derived().maxHp,battle.hp+heal);float('+'+heal,-1,'heal');return true}
function enemyTurn(){const alive=battle.enemies.filter(e=>e.hp>0);if(!alive.length)return;const e=alive[Math.floor(Math.random()*alive.length)],damage=Math.max(1,Math.round((5+e.lv*1.5)*(e.elite?1.4:1)));battle.hp=Math.max(0,battle.hp-damage);$('#fighter').classList.remove('hurt');void $('#fighter').offsetWidth;$('#fighter').classList.add('hurt');float('-'+damage,-1,'enemyDamage');if(battle.hp<=0){paused=true;$('#action').textContent='敗北 — 町で再起';setTimeout(()=>{s.gold=Math.floor(s.gold*.95);s.potions=Math.max(s.potions,2);paused=false;makeBattle()},1300)}}
function stepAction(){if(paused)return;const key=s.queue[battle.index%s.queue.length],sk=SKILLS[key];battle.index++;if(sk.potion){if(usePotion())timers[key]=sk.cd;return}if((timers[key]||0)>0||battle.cp<sk.cost)return;battle.cp-=sk.cost;timers[key]=sk.cd*derived().delay;attack(sk)}
function kill(e){s.kills++;s.gold+=3+e.lv;if(Math.random()<.3+s.stats.luck*.002)drop();if(battle.enemies.every(x=>x.hp<=0)){const gain=8+s.wave*2;s.xp+=gain;while(s.xp>=s.xpNeed){s.xp-=s.xpNeed;s.level++;s.points+=4;s.xpNeed=Math.round(s.xpNeed*1.12+9);toast('LEVEL UP  Lv '+s.level)}s.wave++;save();setTimeout(makeBattle,450/speed)}}
function update(dt){if(paused)return;dt*=speed;const d=derived();battle.hp=Math.min(d.maxHp,battle.hp+d.regen*dt);battle.cp=Math.min(d.maxCp,battle.cp+d.cpRegen*dt);Object.keys(timers).forEach(k=>timers[k]=Math.max(0,timers[k]-dt));battle.wait-=dt;if(battle.wait<=0){stepAction();battle.wait=.72*d.delay}if(Math.random()<dt*.48)enemyTurn();updateUI();renderQueue()}
function renderEnemies(){$('#enemies').innerHTML=battle.enemies.map(e=>'<div class="enemy '+(e.elite?'elite':'')+'" data-id="'+e.id+'"><div class="mob"><i class="eyes"></i></div><label>'+(e.elite?'ELITE ':'')+'Lv'+e.lv+'<span class="hp"><em style="width:100%"></em></span></label></div>').join('')}
function updateEnemy(e){const el=document.querySelector('.enemy[data-id="'+e.id+'"]');if(!el)return;el.querySelector('em').style.width=(e.hp/e.max*100)+'%';if(e.hp<=0)el.classList.add('dead')}
function hitEnemy(id){const el=document.querySelector('.enemy[data-id="'+id+'"]');if(!el)return;el.classList.add('hit');setTimeout(()=>el.classList.remove('hit'),120/speed)}
function float(value,id,cls=''){const box=document.createElement('b');box.className='float '+cls;box.textContent=value;if(id<0){box.style.left='29%';box.style.top='45%'}else{const el=document.querySelector('.enemy[data-id="'+id+'"]');const r=el.getBoundingClientRect(),stage=$('.stage').getBoundingClientRect();box.style.left=(r.left-stage.left+r.width/2)+'px';box.style.top=(r.top-stage.top+10)+'px'}$('#damageLayer').appendChild(box);setTimeout(()=>box.remove(),850/speed)}
function updateUI(){const d=derived();$('#level').textContent='Lv '+s.level;$('#gold').textContent=s.gold+' G';$('#wave').textContent='WAVE '+s.wave;$('#area').textContent='灰の街道 '+Math.ceil(s.wave/10);$('#hpBar').style.width=(battle.hp/d.maxHp*100)+'%';$('#cpBar').style.width=(battle.cp/d.maxCp*100)+'%';$('#xpBar').style.width=(s.xp/s.xpNeed*100)+'%';$('#hpText').textContent=Math.ceil(battle.hp)+' / '+Math.round(d.maxHp);$('#cpText').textContent=Math.floor(battle.cp)+' / '+Math.round(d.maxCp);$('#xpText').textContent=s.xp+' / '+s.xpNeed;$('#potions').textContent=s.potions;$('#lootCount').textContent=s.inventory.length}
function renderQueue(){$('#queue').innerHTML=s.queue.map((k,i)=>{const x=SKILLS[k],cd=Math.max(0,timers[k]||0);return '<button class="skill '+(i===selected?'selected ':'')+(battle.index%s.queue.length===i?'active ':'')+(x.potion?'potion':'')+'" data-i="'+i+'"><span class="icon">'+x.icon+'</span><b>'+x.name+'</b><small>'+(x.potion?'AUTO':x.cost+' CP')+'</small><i class="cool" style="height:'+(cd/x.cd*100)+'%"></i></button>'}).join('')}
function toast(t){$('#action').textContent=t}
function inventory(){openModal('戦利品',s.inventory.length?s.inventory.map(it=>'<article class="item '+it.rarity+'"><b>'+it.name+'</b><small>要求Lv '+it.req+'</small><ul>'+it.ops.map(o=>'<li>['+o.rank+'] '+o.name+' +'+o.value+o.suffix+'</li>').join('')+'</ul><button data-equip="'+it.id+'" '+(it.req>s.level?'disabled':'')+'>'+(s.weapon&&s.weapon.id===it.id?'装備中':'装備する')+'</button></article>').join(''):'<div class="notice">まだ戦利品はありません</div>')}
function stats(){const d=derived(),names={str:'力',agi:'敏捷',vit:'健康',wis:'知恵',int:'知識',cha:'威厳',luck:'運'};openModal('能力値　残り '+s.points,'<div class="stats">'+Object.keys(names).map(k=>'<button class="stat" data-stat="'+k+'"><span>'+names[k]+'</span><b>'+s.stats[k]+'</b><small>＋</small></button>').join('')+'</div><div class="notice">攻撃 '+Math.round(d.atk)+'　HP '+Math.round(d.maxHp)+'　CP '+Math.round(d.maxCp)+'</div>')}
function openModal(title,html){paused=true;$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden')}
function closeModal(){$('#modal').classList.add('hidden');paused=false}
$('#queue').addEventListener('click',e=>{const b=e.target.closest('.skill');if(!b)return;const i=+b.dataset.i;if(selected<0)selected=i;else{[s.queue[selected],s.queue[i]]=[s.queue[i],s.queue[selected]];selected=-1;save()}renderQueue()});
$('#inventoryBtn').onclick=inventory;$('#statsBtn').onclick=stats;$('#closeModal').onclick=closeModal;$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal()};$('#modalBody').onclick=e=>{const equip=e.target.closest('[data-equip]'),stat=e.target.closest('[data-stat]');if(equip){const it=s.inventory.find(x=>String(x.id)===equip.dataset.equip);if(it&&it.req<=s.level){s.weapon=it;save();inventory()}}if(stat&&s.points>0){s.stats[stat.dataset.stat]++;s.points--;save();stats()}};
$('#pauseBtn').onclick=()=>{paused=!paused;$('#pauseBtn').textContent=paused?'再開':'一時停止'};$('#potionBtn').onclick=()=>{if(!paused&&usePotion()){updateUI();save()}};$('#speedBtn').onclick=()=>{speed=speed===1?2:speed===2?3:1;$('#speedBtn').textContent='速度 ×'+speed};
function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;update(dt);requestAnimationFrame(frame)}makeBattle();renderQueue();requestAnimationFrame(frame);
})();