const $=s=>document.querySelector(s),canvas=$('#game'),ctx=canvas.getContext('2d'),TAU=Math.PI*2,SAVE='tasogare-v2';
const ui={hpBar:$('#hpBar'),hpText:$('#hpText'),cpBar:$('#cpBar'),cpText:$('#cpText'),xpBar:$('#xpBar'),levelText:$('#levelText'),formText:$('#formText'),formIcon:$('#formIcon'),transformText:$('#transformText'),lootCount:$('#lootCount'),pointCount:$('#pointCount'),goldText:$('#goldText'),killText:$('#killText'),targetText:$('#targetText'),questText:$('#questText'),potionCount:$('#potionCount'),message:$('#message'),toast:$('#dropToast'),restart:$('#restart'),stick:$('#stickZone'),knob:$('#stickKnob'),skill1:$('#skill1'),skill2:$('#skill2'),skill1Icon:$('#skill1Icon'),skill2Icon:$('#skill2Icon'),skill1Cost:$('#skill1Cost'),skill2Cost:$('#skill2Cost'),dodge:$('#dodge'),transform:$('#transform'),overlay:$('#overlay'),title:$('#panelTitle'),kicker:$('#panelKicker'),tabs:$('#panelTabs'),body:$('#panelBody')};
const ART={field:new Image(),sword:new Image(),warrior:new Image(),ashfang:new Image(),swordAnim:new Image(),warriorAnim:new Image(),swordWalk64:new Image(),warriorWalk64:new Image(),ashfangWalk64:new Image(),swordSide:new Image(),ashfangSide:new Image(),swordFront:new Image(),swordBack:new Image(),ashfangFront:new Image(),ashfangBack:new Image(),swordAttack4:new Image(),swordAttackFront4:new Image(),swordAttackBack4:new Image(),swordGuard4:new Image()};ART.field.src='./assets/ashwind-field.webp';ART.sword.src='./assets/hero-sword.webp';ART.warrior.src='./assets/hero-warrior.webp';ART.ashfang.src='./assets/ashfang.webp';ART.swordAnim.src='./assets/sword-anim-v3.webp';ART.warriorAnim.src='./assets/warrior-anim-v3.webp';
function keyGreen(img){const c=document.createElement('canvas'),x=c.getContext('2d',{willReadFrequently:true});c.width=img.naturalWidth;c.height=img.naturalHeight;x.drawImage(img,0,0);const d=x.getImageData(0,0,c.width,c.height),a=d.data;for(let i=0;i<a.length;i+=4){const r=a[i],g=a[i+1],b=a[i+2];if(g>150&&g>r*1.32&&g>b*1.25)a[i+3]=0}x.putImageData(d,0,0);return c}ART.swordWalk64.onload=()=>ART.swordWalk64Key=keyGreen(ART.swordWalk64);ART.warriorWalk64.onload=()=>ART.warriorWalk64Key=keyGreen(ART.warriorWalk64);ART.swordSide.onload=()=>ART.swordSideKey=keyGreen(ART.swordSide);ART.ashfangSide.onload=()=>ART.ashfangSideKey=keyGreen(ART.ashfangSide);ART.swordFront.onload=()=>ART.swordFrontKey=keyGreen(ART.swordFront);ART.swordBack.onload=()=>ART.swordBackKey=keyGreen(ART.swordBack);ART.ashfangFront.onload=()=>ART.ashfangFrontKey=keyGreen(ART.ashfangFront);ART.ashfangBack.onload=()=>ART.ashfangBackKey=keyGreen(ART.ashfangBack);ART.swordAttack4.onload=()=>ART.swordAttack4Key=keyGreen(ART.swordAttack4);ART.swordAttackFront4.onload=()=>ART.swordAttackFront4Key=keyGreen(ART.swordAttackFront4);ART.swordAttackBack4.onload=()=>ART.swordAttackBack4Key=keyGreen(ART.swordAttackBack4);ART.swordGuard4.onload=()=>ART.swordGuard4Key=keyGreen(ART.swordGuard4);ART.swordWalk64.src='./assets/sword-walk64-v1.webp';ART.warriorWalk64.src='./assets/warrior-walk64-v1.webp';ART.ashfangWalk64.src='./assets/ashfang-walk64-v1.webp';ART.swordSide.src='./assets/sword-sidewalk-v1.webp';ART.ashfangSide.src='./assets/ashfang-sidewalk-v1.webp';ART.swordFront.src='./assets/sword-frontwalk-consistent-v2.webp';ART.swordBack.src='./assets/sword-backwalk-consistent-v2.webp';ART.ashfangFront.src='./assets/ashfang-frontwalk-v1.webp';ART.ashfangBack.src='./assets/ashfang-backwalk-v1.webp';ART.swordAttack4.src='./assets/sword-attack4-v1.webp';ART.swordAttackFront4.src='./assets/sword-attack-front4-v1.webp';ART.swordAttackBack4.src='./assets/sword-attack-back4-v1.webp';ART.swordGuard4.src='./assets/sword-guard4-v1.webp';
const FORMS={sword:{name:'剣士',icon:'剣',attack:'斬',next:'戦士へ',skills:[['閃','三連閃',10],['盾','守護の構え',14]]},warrior:{name:'戦士',icon:'斧',attack:'砕',next:'剣士へ',skills:[['旋','大旋風',14],['破','鎧砕き',18]]}};
const STAT={str:['力','物理攻撃力'],agi:['敏捷','命中・致命打'],vit:['健康','HP・防御力'],luck:['運','ドロップ・回避・ダブクリ'],int:['知識','魔法攻撃力'],wis:['知恵','魔法・異常抵抗'],cha:['カリスマ','最大CP・抵抗倍率']};
const SLOTS={swordMain:'剣士・主武器',swordSub:'剣士・副装備',warriorMain:'戦士・主武器',warriorSub:'戦士・副装備',head:'頭',body:'鎧',gloves:'手',belt:'腰',boots:'足',neck:'首',ear:'耳',ring1:'指輪1',ring2:'指輪2'};
const BASES=[
['swordMain',['欠けた短剣','青銅の剣','鋼の長剣','白銀の剣','黒曜の剣','金剛剣'],'攻撃',8],['swordSub',['木の小盾','皮張り盾','鉄の盾','騎士盾','黒曜盾','金剛盾'],'防御',3],
['warriorMain',['弱い棍棒','石の大斧','鉄の大剣','白銀の戦斧','黒曜大剣','金剛戦槌'],'攻撃',12],['warriorSub',['粗末な柄飾り','戦士の護符','猛者の印','巨人の印','王者の印','金剛の印'],'攻撃',2],
['head',['布の頭巾','皮兜','鉄兜','白銀兜','黒曜兜','金剛兜'],'防御',2],['body',['擦れた服','皮鎧','鉄鎧','白銀鎧','黒曜鎧','金剛鎧'],'防御',5],
['gloves',['布手袋','皮手袋','鉄籠手','白銀籠手','黒曜籠手','金剛籠手'],'防御',1],['belt',['縄の腰紐','皮ベルト','鉄帯','白銀帯','黒曜帯','金剛帯'],'HP',6],
['boots',['布靴','皮靴','鉄靴','白銀靴','黒曜靴','金剛靴'],'防御',1],['neck',['石の首飾り','銅の首飾り','鉄の首飾り','白銀の首飾り','黒曜の首飾り','金剛の首飾り'],'CP',4],
['ear',['木の耳飾り','銅の耳飾り','鉄の耳飾り','白銀の耳飾り','黒曜の耳飾り','金剛の耳飾り'],'命中',1],['ring',['石の指輪','銅の指輪','鉄の指輪','白銀の指輪','黒曜の指輪','金剛の指輪'],'抵抗',1]];
const OPS=[['str','力','',100,10],['agi','敏捷','',100,10],['vit','健康','',100,10],['luck','運','',82,10],['damage','攻撃','％',65,10],['speed','攻撃速度','％',28,3],['defPct','防御力効率','％',72,10],['hp','最大HP','',80,11],['hpPct','最大HP効率','％',48,6],['hit','攻撃命中','％',55,6],['evade','攻撃回避','％',38,6],['crit','致命打率','％',24,2],['life','HP吸収','％',12,4],['cp','最大CP','',62,11],['drop','魔具入手','％',8,3]];
const input={x:0,y:0};let state,world,last=performance.now(),pointer=null,mode='loot',tab='loot',lootFilter='all';
function fresh(){return{v:2,level:1,xp:0,xpNeed:12,statPoints:0,skillPoints:0,stats:{str:10,agi:10,vit:10,luck:10,int:10,wis:10,cha:10},skills:{sword1:1,sword2:1,warrior1:1,warrior2:1},form:'sword',gold:0,potions:3,kills:0,quest:0,inventory:[],equipment:{},statRespec:1,skillRespec:1}}
function load(){try{const s=JSON.parse(localStorage.getItem(SAVE));return s&&s.v===2?Object.assign(fresh(),s):fresh()}catch(e){return fresh()}}function save(){localStorage.setItem(SAVE,JSON.stringify(state))}
function bonus(){const b={str:0,agi:0,vit:0,luck:0,int:0,wis:0,cha:0,damage:0,speed:0,defPct:0,hp:0,hpPct:0,hit:0,evade:0,crit:0,life:0,cp:0,drop:0,atk:0,def:0};Object.values(state.equipment).forEach(it=>{if(!it)return;if(it.baseStat==='攻撃')b.atk+=it.baseValue;if(it.baseStat==='防御')b.def+=it.baseValue;if(it.baseStat==='HP')b.hp+=it.baseValue;if(it.baseStat==='CP')b.cp+=it.baseValue;if(it.baseStat==='命中')b.hit+=it.baseValue;if(it.baseStat==='抵抗')b.wis+=it.baseValue;it.options.forEach(o=>b[o.key]=(b[o.key]||0)+o.value)});return b}
function derived(){const b=bonus(),s={};Object.keys(state.stats).forEach(k=>s[k]=state.stats[k]+(b[k]||0));const maxHp=Math.floor((105+s.vit*3+b.hp)*(1+b.hpPct/100)),maxCp=35+s.cha*2+b.cp,attack=(5+s.str*.72+b.atk)*(state.form==='sword'?1:1.35)*(1+b.damage/100),defense=(s.vit*.32+b.def)*(1+b.defPct/100);return Object.assign({},s,b,{maxHp,maxCp,attack,defense,move:72+Math.min(16,s.agi*.21),attackCd:(state.form==='sword'?.46:.76)/(1+Math.min(1,b.speed/100)),hitChance:Math.min(.98,.78+s.agi*.003+b.hit/100),evadeChance:Math.min(.48,s.agi*.0015+s.luck*.001+b.evade/100),critChance:Math.min(.5,.04+s.agi*.0015+b.crit/100),doubleChance:Math.min(.12,.005+s.luck*.00045),dropChance:Math.min(.55,.18+s.luck*.0012+b.drop/100),lifeSteal:Math.min(.1,b.life/100)})}
function attackDuration(){const speed=Math.min(1,derived().speed/100),base=state.form==='sword'?.58:.86,min=state.form==='sword'?.34:.5;return Math.max(min,base/(1+speed*.65))}
function reset(){const d=derived();world={w:0,h:0,mapW:0,mapH:0,time:0,paused:false,over:false,spawn:3,shake:0,camera:{x:0,y:0,zoom:.96},enemies:[],drops:[],fx:[],texts:[],player:{x:0,y:0,r:9,hp:d.maxHp,cp:d.maxCp,facing:0,targetId:null,attackCd:0,skill1Cd:0,skill2Cd:0,dodgeCd:0,transformCd:0,invuln:0,guard:0,guardMax:0,dash:0,dashX:1,dashY:0,vx:0,vy:0,animTime:0,attackAnim:0,action:'idle',autoCharge:0}};resize();for(let i=0;i<14;i++)spawn(true);updateHud()}
function resize(){const r=canvas.getBoundingClientRect(),w=Math.round(r.width*10)/10,h=Math.round(r.height*10)/10;if(w<2||h<2)return;const d=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(w*d);canvas.height=Math.round(h*d);ctx.setTransform(d,0,0,d,0,0);world.w=w;world.h=h;if(!world.mapW){world.mapW=Math.max(1800,w*2.15);world.mapH=Math.max(1000,h*2.3)}if(!world.player.x){world.player.x=world.mapW/2;world.player.y=world.mapH/2}const vw=w/world.camera.zoom,vh=h/world.camera.zoom;world.camera.x=clamp(world.player.x-vw/2,0,Math.max(0,world.mapW-vw));world.camera.y=clamp(world.player.y-vh/2,0,Math.max(0,world.mapH-vh))}
function spawn(initial){if(!world.mapW)return;let x,y,tries=0;do{x=35+Math.random()*(world.mapW-70);y=75+Math.random()*(world.mapH-120);tries++}while(Math.hypot(x-world.player.x,y-world.player.y)<125&&tries<40);const lv=clamp(Math.floor(1+state.level*.45+world.time/38),1,100),elite=Math.random()<.08,hp=Math.floor((18+lv*4)*(elite?2.4:1));world.enemies.push({id:Date.now().toString(36)+Math.random().toString(36).slice(2,6),x,y,homeX:x,homeY:y,r:elite?12:9,hp,maxHp:hp,level:lv,speed:elite?17:14,vx:0,vy:0,cd:.5+Math.random(),hit:0,elite,broken:0,mode:'idle',think:1+Math.random()*2,roamX:x,roamY:y,alert:0,step:Math.random()*18,face:1,facing:Math.random()*TAU,attackAnim:0,attackPending:0})}
function nearest(range){let best=null,dist=range;world.enemies.forEach(e=>{const d=Math.max(0,Math.hypot(e.x-world.player.x,e.y-world.player.y)-world.player.r-e.r);if(d<dist){best=e;dist=d}});return best}
function hurt(e,mult,aoe){const d=derived();if(Math.random()>d.hitChance){text(e.x,e.y-18,'MISS','#bbb');return}let n=d.attack*mult*(.9+Math.random()*.2),label='',color='#fff',r=Math.random();if(r<d.doubleChance){n*=4;label='DOUBLE!! ';color='#ff344f'}else if(r<d.doubleChance+d.critChance){n*=2;label='CRITICAL! ';color='#ff5968'}if(e.broken>0)n*=1.25;n=Math.max(1,Math.round(n));e.hp-=n;e.hit=.14;const a=Math.atan2(e.y-world.player.y,e.x-world.player.x);e.x+=Math.cos(a)*(aoe?14:6);e.y+=Math.sin(a)*(aoe?14:6);world.shake=aoe?8:4;text(e.x,e.y-16,label+n,color);world.fx.push({type:'spark',x:e.x,y:e.y,a,life:.25,max:.25});if(d.lifeSteal)world.player.hp=Math.min(d.maxHp,world.player.hp+n*d.lifeSteal)}
function attack(){const p=world.player,range=state.form==='sword'?49:57,duration=attackDuration();if(world.over||world.paused||p.attackCd>0||p.attackAnim>0)return;const t=nearest(range);if(!t)return;p.vx=0;p.vy=0;p.targetId=t.id;p.attackCd=duration;p.attackAnim=duration;p.action=state.form==='sword'?'slash':'smash';p.facing=Math.atan2(t.y-p.y,t.x-p.x);world.fx.push({type:p.action,x:p.x,y:p.y,a:p.facing,delay:duration*.43,life:state.form==='sword'?.28:.36,max:state.form==='sword'?.28:.36});world.enemies.forEach(e=>{const dist=Math.hypot(e.x-p.x,e.y-p.y),a=Math.atan2(e.y-p.y,e.x-p.x);if(dist<=range+p.r+e.r&&Math.abs(delta(a,p.facing))<(state.form==='sword'?.95:.84))hurt(e,1,false)})}
function skill(which){const p=world.player,key=state.form+which,lv=state.skills[key],cost=FORMS[state.form].skills[which-1][2];if(world.paused||world.over||p['skill'+which+'Cd']>0||p.cp<cost)return;p.dash=0;p.vx=0;p.vy=0;p.cp-=cost;p.attackAnim=attackDuration()*(which===1?1.35:1.12);p['skill'+which+'Cd']=which===1?4.2:7.5;if(state.form==='sword'&&which===1){p.action='triple';const t=nearest(135);if(t){p.targetId=t.id;p.facing=Math.atan2(t.y-p.y,t.x-p.x)}world.fx.push({type:'triple',x:p.x,y:p.y,a:p.facing,delay:.15,life:.56,max:.56});world.enemies.forEach(e=>{const dx=e.x-p.x,dy=e.y-p.y,along=dx*Math.cos(p.facing)+dy*Math.sin(p.facing),side=Math.abs(-dx*Math.sin(p.facing)+dy*Math.cos(p.facing));if(along>0&&along<135&&side<32)hurt(e,1.35+lv*.12,true)})}else if(state.form==='sword'){p.action='guard';p.guard=4+lv*.3;p.guardMax=p.guard;notice('守護の構え',600)}else if(which===1){p.action='spin';world.fx.push({type:'spin',x:p.x,y:p.y,a:0,delay:.12,life:.5,max:.5});world.enemies.forEach(e=>{if(Math.hypot(e.x-p.x,e.y-p.y)<118)hurt(e,1.25+lv*.15,true)})}else{p.action='break';const t=nearest(105);if(t){p.targetId=t.id;p.facing=Math.atan2(t.y-p.y,t.x-p.x);hurt(t,1.75+lv*.14,true);t.broken=6+lv;text(t.x,t.y-30,'防御低下','#f0b05a')}world.fx.push({type:'break',x:p.x,y:p.y,a:p.facing,delay:.17,life:.48,max:.48})}updateHud()}
function dodge(){const p=world.player;if(world.paused||world.over||p.dodgeCd>0)return;const m=Math.hypot(input.x,input.y);p.dodgeCd=2.2;p.invuln=.55;p.dash=.2;p.dashX=m>.12?input.x/m:Math.cos(p.facing);p.dashY=m>.12?input.y/m:Math.sin(p.facing)}
function transform(){const p=world.player;if(world.paused||world.over||p.transformCd>0)return;state.form=state.form==='sword'?'warrior':'sword';p.transformCd=2;p.attackCd=.35;p.cp=Math.min(derived().maxCp,p.cp+8);world.fx.push({type:'transform',x:p.x,y:p.y,a:0,life:.65,max:.65});notice(FORMS[state.form].name+'へ変身',700);save();updateHud()}
function enemyHit(e){const p=world.player,d=derived();if(p.invuln>0||Math.random()<d.evadeChance){text(p.x,p.y-22,'回避','#7de0ff');return}const damage=Math.max(1,Math.round((7+e.level*1.15+(e.elite?8:0)-d.defense*.25)*(p.guard>0?.38:1)));p.hp-=damage;p.invuln=.42;world.shake=9;text(p.x,p.y-20,'-'+damage,'#ff5b68');if(p.hp<=0){p.hp=0;world.over=true;ui.message.innerHTML='力尽きた<br><small>戦利品と成長は失われません</small>';ui.message.classList.remove('hidden');ui.restart.classList.remove('hidden')}updateHud()}
function update(dt){
 const p=world.player;p.vx??=0;p.vy??=0;p.targetId??=null;if(world.paused||world.over)return;world.time+=dt;
 ['attackCd','skill1Cd','skill2Cd','dodgeCd','transformCd','invuln','guard','dash','attackAnim'].forEach(k=>p[k]=Math.max(0,p[k]-dt));const tracked=p.targetId&&world.enemies.find(e=>e.id===p.targetId);if(p.attackAnim>0&&tracked)p.facing=Math.atan2(tracked.y-p.y,tracked.x-p.x);if(p.attackAnim===0&&p.guard===0){p.action='idle';p.targetId=null}
 p.cp=Math.min(derived().maxCp,p.cp+dt*2.4);
 let ix=Math.abs(input.x)<.12?0:input.x,iy=Math.abs(input.y)<.12?0:input.y,mag=Math.hypot(ix,iy);
 if(mag>1){ix/=mag;iy/=mag;mag=1}
 const moveInput=mag>.05;
 if(moveInput&&p.attackAnim>0&&p.dash<=0){p.attackAnim=0;p.attackCd=0;p.targetId=null;p.action='idle'}
 const locked=p.attackAnim>0||p.guard>0;
 let targetVx=0,targetVy=0;
 if(p.dash>0){const speed=derived().move*2.15;targetVx=p.dashX*speed;targetVy=p.dashY*speed}
 else if(moveInput&&!locked){const speed=derived().move;targetVx=ix*speed;targetVy=iy*speed;p.facing=Math.atan2(iy,ix)}
 const response=1-Math.exp(-dt*(p.dash>0?28:locked?38:15));
 p.vx+=(targetVx-p.vx)*response;p.vy+=(targetVy-p.vy)*response;
 if(locked){p.vx=0;p.vy=0}
 const playerSpeed=Math.hypot(p.vx,p.vy);p.animTime+=playerSpeed*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;
 p.x=clamp(p.x,p.r,world.mapW-p.r);p.y=clamp(p.y,p.r,world.mapH-p.r);
 const viewW=world.w/world.camera.zoom,viewH=world.h/world.camera.zoom,targetCamX=clamp(p.x-viewW/2,0,Math.max(0,world.mapW-viewW)),targetCamY=clamp(p.y-viewH/2,0,Math.max(0,world.mapH-viewH)),follow=1-Math.pow(.0008,dt);world.camera.x+=(targetCamX-world.camera.x)*follow;world.camera.y+=(targetCamY-world.camera.y)*follow;
 world.spawn-=dt;if(world.spawn<=0&&world.enemies.length<18){spawn(false);world.spawn=2.8}
 let alerted=0;
 world.enemies.forEach(e=>{
   e.vx??=0;e.vy??=0;e.hit=Math.max(0,e.hit-dt);e.broken=Math.max(0,e.broken-dt);e.alert=Math.max(0,e.alert-dt);e.cd-=dt;e.think-=dt;const pending=e.attackPending;e.attackAnim=Math.max(0,e.attackAnim-dt);e.attackPending=Math.max(0,e.attackPending-dt);if(pending>0&&e.attackPending===0&&Math.hypot(p.x-e.x,p.y-e.y)<p.r+e.r+25)enemyHit(e);
   const dx=p.x-e.x,dy=p.y-e.y,dist=Math.hypot(dx,dy)||1,homeDist=Math.hypot(e.x-e.homeX,e.y-e.homeY),aggro=e.elite?245:210,attackRange=p.r+e.r+15;let targetVx=0,targetVy=0;
   if((e.mode==='idle'||e.mode==='wander')&&dist<aggro){e.mode='aggro';e.alert=.75;text(e.x,e.y-24,'！','#ffd86b')}
   if(e.mode==='aggro'){
     alerted++;
     if(dist>330||homeDist>360){e.mode='return';e.think=1;e.attackAnim=0;e.attackPending=0}
     else if(e.attackAnim>0){}
     else if(dist>attackRange){targetVx=dx/dist*e.speed;targetVy=dy/dist*e.speed;e.facing=Math.atan2(dy,dx)}
     else if(e.cd<=0&&e.attackAnim<=0){e.facing=Math.atan2(dy,dx);e.cd=e.elite?1.25:1.7;e.attackAnim=.7;e.attackPending=.36}
   }else if(e.mode==='return'){
     const rx=e.homeX-e.x,ry=e.homeY-e.y,rd=Math.hypot(rx,ry)||1;
     if(rd<5){e.mode='idle';e.think=1+Math.random()*2}else{targetVx=rx/rd*e.speed*.8;targetVy=ry/rd*e.speed*.8;e.facing=Math.atan2(ry,rx)}
   }else if(e.mode==='wander'){
     const wx=e.roamX-e.x,wy=e.roamY-e.y,wd=Math.hypot(wx,wy)||1;
     if(wd<4||e.think<=0){e.mode='idle';e.think=1.4+Math.random()*2.6}else{targetVx=wx/wd*e.speed*.28;targetVy=wy/wd*e.speed*.28;e.facing=Math.atan2(wy,wx)}
   }else if(e.think<=0){
     const a=Math.random()*TAU,r=18+Math.random()*34;e.roamX=clamp(e.homeX+Math.cos(a)*r,20,world.mapW-20);e.roamY=clamp(e.homeY+Math.sin(a)*r,20,world.mapH-20);e.mode='wander';e.think=3+Math.random()*3
   }
   const eResponse=1-Math.exp(-dt*(e.mode==='aggro'?10:6));e.vx+=(targetVx-e.vx)*eResponse;e.vy+=(targetVy-e.vy)*eResponse;if(e.attackAnim>0){e.vx=0;e.vy=0}const eSpeed=Math.hypot(e.vx,e.vy);e.x+=e.vx*dt;e.y+=e.vy*dt;e.step+=eSpeed*dt;
   e.x=clamp(e.x,e.r,world.mapW-e.r);e.y=clamp(e.y,e.r,world.mapH-e.r);
 });
 for(let i=0;i<world.enemies.length;i++)for(let j=i+1;j<world.enemies.length;j++){const a=world.enemies[i],b=world.enemies[j],dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||1,min=a.r+b.r+7;if(d<min){const push=(min-d)*.5;a.x-=dx/d*push;b.x+=dx/d*push;a.y-=dy/d*push;b.y+=dy/d*push}}
 const autoTarget=nearest(state.form==='sword'?49:57);if(autoTarget&&!moveInput&&playerSpeed<4&&p.attackCd<=0&&p.attackAnim<=0){attack();p.autoCharge=0}else if(!autoTarget)p.autoCharge=0;
 ui.targetText.textContent=alerted?'警戒 '+alerted+'体':'未警戒';
 const dead=world.enemies.filter(e=>e.hp<=0);dead.forEach(kill);if(dead.length)world.enemies=world.enemies.filter(e=>e.hp>0);
 world.drops.forEach(d=>{d.age+=dt;d.height+=d.velocity*dt;d.velocity-=240*dt;if(d.height<0){d.height=0;d.velocity=Math.abs(d.velocity)*.32;if(d.velocity<12)d.velocity=0}d.spin+=dt*3;const near=Math.hypot(d.x-p.x,d.y-p.y)<48;if((d.age>.45&&near)||d.age>5.5)pickupDrop(d)});
 world.drops=world.drops.filter(d=>!d.picked);world.fx.forEach(q=>{if(q.delay>0)q.delay-=dt;else q.life-=dt});world.fx=world.fx.filter(q=>q.life>0);world.texts.forEach(q=>q.life-=dt);world.texts.forEach(q=>q.y-=25*dt);world.texts=world.texts.filter(q=>q.life>0);world.shake*=.84;
 [[ui.skill1,'skill1Cd'],[ui.skill2,'skill2Cd'],[ui.dodge,'dodgeCd'],[ui.transform,'transformCd']].forEach(x=>x[0].classList.toggle('cooling',p[x[1]]>0));
}
function kill(e){state.kills++;state.quest++;state.xp+=2+Math.floor(e.level/3)+(e.elite?4:0);state.gold+=2+e.level+(e.elite?e.level*2:0);while(state.xp>=state.xpNeed){state.xp-=state.xpNeed;state.level++;state.xpNeed=Math.ceil(state.xpNeed*1.28+5);state.statPoints+=4;state.skillPoints++;const d=derived();world.player.hp=d.maxHp;world.player.cp=d.maxCp;notice('LEVEL UP '+state.level+'<br><small>能力 +4 / スキル +1</small>',1500)}if(state.quest>=8){state.quest=0;state.gold+=50;state.potions++;notice('討伐依頼 達成<br><small>50G・回復薬を獲得</small>',1300)}world.fx.push({type:'death',x:e.x,y:e.y,a:0,life:.45,max:.45});if(state.inventory.length+world.drops.length<20&&(Math.random()<derived().dropChance*(e.elite?1.8:1)||state.kills%3===0)){const it=makeItem(e.level,e.elite);world.drops.push({x:e.x,y:e.y,item:it,age:0,height:0,velocity:105,spin:0,picked:false})}save();updateHud()}
function pickupDrop(d){if(d.picked||state.inventory.length>=20)return;d.picked=true;state.inventory.unshift(d.item);world.fx.push({type:'pickup',x:d.x,y:d.y,a:0,life:.5,max:.5});toast(d.item);save();updateHud()}
function makeItem(enemyLv,elite){const b=pick(BASES),tier=clamp(Math.floor(enemyLv/20),0,5),baseReq=tier*20,baseValue=Math.round(b[3]*(1+tier*.9)*(b[0].includes('Main')?1+enemyLv*.012:1)),luck=derived().luck,r=Math.random(),p3=Math.min(.16,.025+luck*.00045+(elite?.07:0)),p2=Math.min(.38,.12+luck*.0007+(elite?.1:0));let count=r<p3?3:r<p3+p2?2:Math.random()<.42?1:0,options=[];for(let i=0;i<count;i++)options.push(makeOp());const req=options.map(o=>o.req).sort((a,c)=>c-a);let add=req.length===1?req[0]:req.length===2?req[0]+req[1]*2/3:req.length===3?req[0]+req[1]*2/3+req[2]/3:0;return{id:Date.now().toString(36)+Math.random().toString(36).slice(2,7),name:b[1][tier],slot:b[0],baseStat:b[2],baseValue,requiredLevel:baseReq+Math.floor(add),enemyLevel:enemyLv,options,locked:false,new:true}}
function makeOp(){const o=weighted(OPS),key=o[0],name=o[1],unit=o[2],coef=o[3],max=o[4];let level=1;while(level<max&&Math.random()<.32)level++;if(Math.random()<.025)level=Math.min(max,level+1+Math.floor(Math.random()*3));const scales={speed:9,crit:2,life:1,hit:1,evade:1,drop:5,damage:5,defPct:5,hpPct:5},scale=scales[key]||2;let value=Math.round(scale*level*(.8+Math.random()*.45));if(['str','agi','vit','luck','hp','cp'].includes(key))value+=level*2;return{key,name,level,value,unit,req:Math.round(level*level*.8+level*2+(coef<20?18:0)),high:coef<20||level>=7}}
function draw(){const w=world.w,h=world.h,p=world.player,c=world.camera,z=c.zoom;ctx.save();ctx.clearRect(0,0,w,h);ctx.translate((Math.random()-.5)*world.shake,(Math.random()-.5)*world.shake);ctx.save();ctx.scale(z,z);ctx.translate(-c.x,-c.y);if(ART.field.complete&&ART.field.naturalWidth){const sc=Math.max(world.mapW/ART.field.naturalWidth,world.mapH/ART.field.naturalHeight),iw=ART.field.naturalWidth*sc,ih=ART.field.naturalHeight*sc;ctx.drawImage(ART.field,(world.mapW-iw)/2,(world.mapH-ih)/2,iw,ih)}else{ctx.fillStyle='#17231d';ctx.fillRect(0,0,world.mapW,world.mapH)}world.enemies.forEach(drawEnemy);world.drops.forEach(drawDrop);drawAttackGuide(p);world.fx.filter(f=>!f.delay||f.delay<=0).forEach(drawFx);drawPlayer(p);world.texts.forEach(t=>{ctx.globalAlpha=Math.min(1,t.life*2);ctx.fillStyle=t.color;ctx.font='900 11px system-ui';ctx.textAlign='center';ctx.shadowColor='#000';ctx.shadowBlur=3;ctx.fillText(t.value,t.x,t.y)});ctx.globalAlpha=1;ctx.restore();const px=(p.x-c.x)*z,py=(p.y-c.y)*z,shade=ctx.createRadialGradient(px,py,35,px,py,Math.max(w,h)*.7);shade.addColorStop(0,'rgba(12,22,20,.02)');shade.addColorStop(1,'rgba(2,5,7,.66)');ctx.fillStyle=shade;ctx.fillRect(0,0,w,h);ctx.restore();drawMiniMap()}

function drawMiniMap(){const w=132,h=78,x=8,y=64,head=15,innerY=y+head,innerH=h-head-3,scaleX=(w-6)/world.mapW,scaleY=innerH/world.mapH,p=world.player,c=world.camera,viewW=world.w/c.zoom,viewH=world.h/c.zoom;ctx.save();ctx.shadowColor='#43d8ff88';ctx.shadowBlur=10;ctx.fillStyle='#173d4eee';ctx.strokeStyle='#a5ecff';ctx.lineWidth=1.3;ctx.beginPath();ctx.roundRect(x,y,w,h,6);ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle='#3480a0';ctx.beginPath();ctx.roundRect(x+1,y+1,w-2,head,5);ctx.fill();ctx.fillStyle='#f4fdff';ctx.font='900 9px system-ui';ctx.textAlign='left';ctx.fillText('MAP',x+7,y+11);ctx.fillStyle='#c8f2ff';ctx.font='700 6px system-ui';ctx.textAlign='right';ctx.fillText('敵・視野',x+w-7,y+10);ctx.save();ctx.beginPath();ctx.rect(x+3,innerY,w-6,innerH);ctx.clip();ctx.fillStyle='#5e9a8388';ctx.fillRect(x+3,innerY,w-6,innerH);ctx.strokeStyle='#e4fbffcc';ctx.lineWidth=.8;ctx.strokeRect(x+3+c.x*scaleX,innerY+c.y*scaleY,viewW*scaleX,viewH*scaleY);world.drops.forEach(d=>{ctx.fillStyle='#ffe58a';ctx.fillRect(x+3+d.x*scaleX-1,innerY+d.y*scaleY-1,2,2)});world.enemies.forEach(e=>{ctx.fillStyle=e.elite?'#e0a0ff':e.mode==='aggro'?'#ff7777':'#ffc3c3';ctx.beginPath();ctx.arc(x+3+e.x*scaleX,innerY+e.y*scaleY,e.elite?2.1:1.55,0,TAU);ctx.fill()});ctx.fillStyle='#fff3a6';ctx.beginPath();ctx.arc(x+3+p.x*scaleX,innerY+p.y*scaleY,3,0,TAU);ctx.fill();ctx.restore();ctx.restore()}
function dirRow(a){return((Math.round((Math.PI/2-a)/(Math.PI/4))%8)+8)%8}
function drawAttackGuide(p){const range=(state.form==='sword'?49:57)+p.r,target=nearest(range+20),active=!!nearest(state.form==='sword'?49:57),swing=p.attackAnim>0;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.facing);const half=state.form==='sword'?.95:.84;ctx.strokeStyle=swing?'#ffe69a88':active?'#e8c76677':'#b8d6db32';ctx.lineWidth=swing?1.7:1;ctx.beginPath();ctx.arc(0,0,range,-half,half);ctx.stroke();ctx.beginPath();ctx.arc(0,0,range-3,-half+.12,half-.12);ctx.stroke();if(target){ctx.fillStyle=active?'#efd36a99':'#d8f0f044';ctx.beginPath();ctx.arc(Math.min(range,target?Math.hypot(target.x-p.x,target.y-p.y):range),0,2.2,0,TAU);ctx.fill()}ctx.restore()}
function drawPlayer(p){const attacking=p.attackAnim>0,moving=Math.hypot(p.vx||0,p.vy||0)>3||p.dash>0,duration=attackDuration(),phase=attacking?clamp(1-p.attackAnim/duration,0,1):0,action=p.action||'idle',step=moving?Math.floor(p.animTime/8.4)%8:0,row=dirRow(p.facing),bounce=moving&&!attacking?Math.sin((p.animTime/8.4)*Math.PI)*1.15:Math.sin(world.time*2)*.35,impact=Math.sin(phase*Math.PI),lunge=attacking?impact*(action==='triple'?7:action==='smash'||action==='break'?8:5):0,isSword=state.form==='sword',guarding=isSword&&p.guard>0,horizontal=Math.abs(Math.cos(p.facing))>.58,attackStrip=horizontal?ART.swordAttack4Key:(Math.sin(p.facing)>0?ART.swordAttackFront4Key:ART.swordAttackBack4Key),actionStrip=guarding?ART.swordGuard4Key:(isSword&&attacking&&(action==='slash'||action==='triple')?(attackStrip||ART.swordAttack4Key):null),actionPhase=guarding?clamp(1-p.guard/(p.guardMax||1),0,1):phase,actionFrame=guarding?Math.min(2,Math.floor(actionPhase*7)):action==='triple'?Math.min(3,Math.floor(((phase*3)%1)*4)):Math.min(3,Math.floor(phase*4)),sheet=isSword?(ART.swordWalk64Key||ART.swordWalk64):(ART.warriorWalk64Key||ART.warriorWalk64),strip=isSword?(horizontal?ART.swordSideKey:(Math.sin(p.facing)>0?ART.swordFrontKey:ART.swordBackKey)):null,useStrip=!!strip,front=strip===ART.swordFrontKey,back=strip===ART.swordBackKey;ctx.save();ctx.translate(p.x+Math.cos(p.facing)*lunge,p.y+Math.sin(p.facing)*lunge+bounce);if(actionStrip&&!guarding&&horizontal&&Math.cos(p.facing)>0)ctx.scale(-1,1);else if(!actionStrip&&useStrip&&horizontal&&Math.cos(p.facing)>0)ctx.scale(-1,1);if(p.invuln>0&&Math.floor(p.invuln*18)%2===0)ctx.globalAlpha=.35;ctx.shadowColor=isSword?'#62cfff':'#f0a34e';ctx.shadowBlur=5;if(actionStrip){const sw=actionStrip.width/4,sh=actionStrip.height,dw=71,dh=94;ctx.drawImage(actionStrip,actionFrame*sw,0,sw,sh,-dw/2,-dh+18,dw,dh)}else if(useStrip){const sw=strip.width/8,sy=strip.height*.11,sh=strip.height*.78,dw=front?72:back?75:80,dh=front?94:back?110:112;ctx.drawImage(strip,step*sw,sy,sw,sh,-dw/2,-dh+21,dw,dh)}else if(sheet&&sheet.width){const sw=sheet.width/8,sh=sheet.height/8,dw=isSword?68:70,dh=isSword?91:94;ctx.drawImage(sheet,step*sw,row*sh,sw,sh,-dw/2,-dh+20,dw,dh)}else{const still=isSword?ART.sword:ART.warrior;if(still.complete&&still.naturalWidth){const dw=68,dh=91;ctx.drawImage(still,-dw/2,-dh+20,dw,dh)}}ctx.restore();drawActionPose(p,action,attacking?phase:.5,isSword)}
function drawActionPose(p,action,phase,isSword){if(action==='idle'||(isSword&&(action==='slash'||action==='triple'||action==='guard'||p.guard>0)))return;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.facing);ctx.globalCompositeOperation='lighter';if(action==='smash'||action==='break'){const rise=Math.sin(phase*Math.PI);ctx.rotate(-.6+phase*1.2);ctx.strokeStyle=action==='break'?'#ffca72':'#ffc267';ctx.shadowColor=ctx.strokeStyle;ctx.shadowBlur=16;ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(3,-14);ctx.lineTo(37,-50);ctx.stroke();if(rise>.52){ctx.strokeStyle='#ffe3a8';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(20,-2);ctx.lineTo(42,15);ctx.moveTo(25,-4);ctx.lineTo(54,5);ctx.stroke()}}else if(action==='spin'){ctx.strokeStyle='#ffc267';ctx.shadowColor='#ffc267';ctx.shadowBlur=14;ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,39,0,TAU);ctx.stroke()}ctx.restore()}
function drawDrop(d){const count=d.item.options.length,color=['#d7dde1','#4aa8ff','#f2c84b','#b66cff'][count],y=d.y-d.height;ctx.save();ctx.globalCompositeOperation='lighter';const beam=ctx.createLinearGradient(0,y-80,0,y+12);beam.addColorStop(0,'transparent');beam.addColorStop(1,color+'aa');ctx.fillStyle=beam;ctx.fillRect(d.x-9,y-80,18,92);ctx.globalCompositeOperation='source-over';ctx.strokeStyle=color;ctx.lineWidth=2;ctx.globalAlpha=.45+.25*Math.sin(d.spin*2);ctx.beginPath();ctx.ellipse(d.x,d.y+8,18+Math.sin(d.spin)*3,7,0,0,TAU);ctx.stroke();ctx.globalAlpha=1;ctx.translate(d.x,y);ctx.rotate(Math.sin(d.spin)*.18);ctx.shadowColor=color;ctx.shadowBlur=14;ctx.fillStyle=color;if(d.item.slot.includes('Main')){ctx.fillRect(-3,-15,6,25);ctx.beginPath();ctx.moveTo(0,-22);ctx.lineTo(-7,-11);ctx.lineTo(7,-11);ctx.fill()}else if(d.item.slot==='ring'){ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,-5,8,0,TAU);ctx.stroke()}else{ctx.beginPath();ctx.moveTo(-11,-12);ctx.lineTo(11,-12);ctx.lineTo(8,9);ctx.lineTo(0,15);ctx.lineTo(-8,9);ctx.closePath();ctx.fill()}ctx.restore();ctx.fillStyle=color;ctx.font='900 9px system-ui';ctx.textAlign='center';ctx.shadowColor='#000';ctx.shadowBlur=4;ctx.fillText(d.item.name,d.x,d.y+28)}
function drawEnemy(e){const moving=e.mode==='aggro'||e.mode==='return'||e.mode==='wander',attacking=e.attackAnim>0,phase=attacking?clamp(1-e.attackAnim/.7,0,1):0,lunge=attacking?Math.sin(phase*Math.PI)*e.r*1.35:0,bob=moving&&!attacking?Math.sin(e.step*.45)*1.05:0,tilt=moving&&!attacking?Math.sin(e.step*.28)*.028:0,frame=attacking?Math.min(7,Math.floor(phase*8)):(moving?Math.floor(e.step/2.4)%8:0),row=dirRow(e.facing),sheet=ART.ashfangWalk64,horizontal=Math.abs(Math.cos(e.facing))>.58,strip=horizontal?ART.ashfangSideKey:(Math.sin(e.facing)>0?ART.ashfangFrontKey:ART.ashfangBackKey),useStrip=!!strip;ctx.save();ctx.translate(e.x+Math.cos(e.facing)*lunge,e.y+Math.sin(e.facing)*lunge+bob);ctx.rotate(tilt);if(attacking){const squash=Math.sin(phase*Math.PI);ctx.scale(1+squash*.09,1-squash*.035)}if(useStrip&&horizontal&&Math.cos(e.facing)>0)ctx.scale(-1,1);ctx.shadowColor=e.elite?'#c678ff':e.mode==='aggro'?'#e65757':'#38cfe3';ctx.shadowBlur=e.hit?16:e.elite?10:4;if(e.hit)ctx.globalAlpha=.55;if(useStrip){const sw=strip.width/8,sy=strip.height*.12,sh=strip.height*.76,scale=horizontal?1:.92;ctx.drawImage(strip,frame*sw,sy,sw,sh,-e.r*3.7*scale,-e.r*3.6*scale,e.r*7.4*scale,e.r*7.1*scale)}else if(sheet&&sheet.width){const sw=sheet.width/8,sh=sheet.height/8;ctx.drawImage(sheet,frame*sw,row*sh,sw,sh,-e.r*3.25,-e.r*2.45,e.r*6.5,e.r*4.35)}else if(ART.ashfang.complete&&ART.ashfang.naturalWidth)ctx.drawImage(ART.ashfang,-e.r*2.7,-e.r*1.9,e.r*5.4,e.r*3.55);ctx.restore();ctx.fillStyle='#170b0e';ctx.fillRect(e.x-e.r*1.25,e.y+e.r+4,e.r*2.5,3);ctx.fillStyle=e.broken>0?'#dfad45':'#e24c5d';ctx.fillRect(e.x-e.r*1.25,e.y+e.r+4,e.r*2.5*Math.max(0,e.hp/e.maxHp),3);if(e.mode==='aggro'){ctx.strokeStyle='#e85e5e88';ctx.lineWidth=1;ctx.beginPath();ctx.arc(e.x,e.y,e.r+7,0,TAU);ctx.stroke()}if(e.elite){ctx.fillStyle='#e4b8ff';ctx.font='900 7px system-ui';ctx.textAlign='center';ctx.fillText('エリート Lv'+e.level,e.x,e.y-e.r*1.8-7)}}
function drawFx(f){const a=f.life/f.max,age=1-a;ctx.save();ctx.translate(f.x,f.y);ctx.rotate(f.a||0);ctx.globalCompositeOperation='lighter';ctx.globalAlpha=Math.min(1,a*1.8);if(f.type==='slash'){ctx.shadowColor='#ffe4a1';ctx.shadowBlur=20;ctx.strokeStyle='#fff0c6';ctx.lineWidth=5+age*3;ctx.beginPath();ctx.arc(3,0,48+age*12,-1.05,1.12);ctx.stroke();ctx.strokeStyle='#ffad4c';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(3,0,55+age*16,-1.12,1.2);ctx.stroke()}else if(f.type==='triple'){for(let i=0;i<3;i++){const q=clamp((age*3-i)*1.6,0,1);if(!q)continue;ctx.save();ctx.rotate((i-1)*.2);ctx.globalAlpha=q*(1-q*.25);ctx.shadowColor='#6edcff';ctx.shadowBlur=22;ctx.strokeStyle='#b7f1ff';ctx.lineWidth=5;ctx.beginPath();ctx.arc(12,0,54+i*12,-1.18,1.03);ctx.stroke();ctx.restore()}}else if(f.type==='smash'||f.type==='break'){ctx.shadowColor=f.type==='break'?'#ffd27a':'#ffb95f';ctx.shadowBlur=24;ctx.strokeStyle=f.type==='break'?'#ffe3aa':'#ffc26e';ctx.lineWidth=8*(1-age*.35);ctx.beginPath();ctx.arc(0,0,44+age*42,-.9,1.05);ctx.stroke();for(let i=0;i<5;i++){ctx.save();ctx.rotate((i-2)*.24);ctx.strokeStyle='#ffe7bb';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(42+age*28,0);ctx.lineTo(61+age*44,0);ctx.stroke();ctx.restore()}}else if(f.type==='spin'){ctx.shadowColor='#ffc267';ctx.shadowBlur=24;ctx.strokeStyle='#ffdf9a';ctx.lineWidth=10*a+3;ctx.beginPath();ctx.arc(0,0,102*age+24,0,TAU);ctx.stroke();ctx.strokeStyle='#ffb34f';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,126*age+31,0,TAU);ctx.stroke()}else if(f.type==='thrust'){ctx.shadowColor='#7fe2ff';ctx.shadowBlur=22;ctx.strokeStyle='#c5f7ff';ctx.lineWidth=7+age*7;ctx.beginPath();ctx.moveTo(4,0);ctx.lineTo(72+age*78,0);ctx.stroke();ctx.strokeStyle='#2a9eff';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,-8);ctx.lineTo(92+age*54,-8);ctx.moveTo(0,8);ctx.lineTo(92+age*54,8);ctx.stroke()}else if(f.type==='spark'){ctx.rotate(age*5);ctx.shadowColor='#fff2b0';ctx.shadowBlur=10;ctx.fillStyle='#fff2bd';for(let i=0;i<4;i++){ctx.rotate(Math.PI/2);ctx.fillRect(4+age*14,-1.5,7,3)}}else if(f.type==='death'){ctx.shadowColor='#78d6d2';ctx.shadowBlur=16;ctx.strokeStyle='#78d6d2';ctx.lineWidth=8*a;ctx.beginPath();ctx.arc(0,0,36*(1-a)+8,0,TAU);ctx.stroke()}else if(f.type==='pickup'){ctx.shadowColor='#ffe39a';ctx.shadowBlur=16;ctx.strokeStyle='#ffe39a';ctx.lineWidth=5*a;ctx.beginPath();ctx.arc(0,0,30*(1-a)+5,0,TAU);ctx.stroke()}else if(f.type==='guard'||f.type==='guardBurst'||f.type==='transform'){const guard=f.type==='guard'||f.type==='guardBurst';ctx.shadowColor=guard?'#76cfff':'#f6d98a';ctx.shadowBlur=18;ctx.strokeStyle=guard?'#9cecff':'#f6d98a';ctx.lineWidth=f.type==='guardBurst'?7*(1-age):guard?3:5;ctx.beginPath();ctx.arc(0,0,f.type==='guardBurst'?20+age*58:guard?28:55*(1-a)+18,0,TAU);ctx.stroke();if(f.type==='guardBurst'){ctx.strokeStyle='#dcfbff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,34+age*66,0,TAU);ctx.stroke()}}ctx.restore()}
function text(x,y,value,color){world.texts.push({x,y,value,color,life:.8})}function updateHud(){const d=derived(),p=world.player,f=FORMS[state.form];p.hp=Math.min(p.hp,d.maxHp);p.cp=Math.min(p.cp,d.maxCp);ui.hpBar.style.width=p.hp/d.maxHp*100+'%';ui.hpText.textContent=Math.ceil(p.hp)+' / '+d.maxHp;ui.cpBar.style.width=p.cp/d.maxCp*100+'%';ui.cpText.textContent=Math.floor(p.cp)+' / '+d.maxCp+' CP';ui.xpBar.style.width=state.xp/state.xpNeed*100+'%';ui.levelText.textContent='Lv'+state.level;ui.formText.textContent=f.name+' Lv'+state.level;ui.formIcon.textContent=f.icon;ui.formIcon.style.opacity='0';const badge=$('#formBadge');badge.style.backgroundImage="linear-gradient(#0b111144,#0b111144),url('./assets/hero-"+state.form+".webp')";badge.style.backgroundSize='cover';badge.style.backgroundPosition='center 18%';ui.transformText.textContent=f.next;ui.skill1Icon.textContent=f.skills[0][0];ui.skill2Icon.textContent=f.skills[1][0];ui.skill1Cost.textContent=f.skills[0][2];ui.skill2Cost.textContent=f.skills[1][2];ui.lootCount.textContent=state.inventory.filter(i=>i.new).length;ui.pointCount.textContent=state.statPoints+state.skillPoints;ui.goldText.textContent=state.gold+' G';ui.killText.textContent='討伐 '+state.kills;ui.questText.textContent='魔物を '+state.quest+' / 8 体倒す';ui.potionCount.textContent=state.potions}
function notice(v,ms){ui.message.innerHTML=v;ui.message.classList.remove('hidden');clearTimeout(notice.t);notice.t=setTimeout(()=>{if(!world.over)ui.message.classList.add('hidden')},ms)}function toast(it){ui.toast.innerHTML=(it.options.length===3?'✦ ':'')+it.name+'<br><small>'+it.options.length+'オプション・要求Lv '+it.requiredLevel+'</small>';ui.toast.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>ui.toast.classList.add('hidden'),1800)}
function openPanel(m,t){mode=m;tab=t;world.paused=true;ui.overlay.classList.remove('hidden');render()}function closePanel(){ui.overlay.classList.add('hidden');world.paused=false;state.inventory.forEach(i=>i.new=false);save();updateHud()}
function render(){const tabs=mode==='loot'?[['loot','拾った装備'],['equipment','装着中']]:[['stats','能力'],['skills','スキル'],['details','戦闘値']];ui.title.textContent=mode==='loot'?'装備管理':'キャラクター育成';ui.kicker.textContent=mode==='loot'?'所持 '+state.inventory.length+' / 20':'未使用 能力'+state.statPoints+'・スキル'+state.skillPoints;ui.tabs.innerHTML=tabs.map(x=>'<button data-tab="'+x[0]+'" class="'+(tab===x[0]?'active':'')+'">'+x[1]+'</button>').join('');if(tab==='loot')lootPanel();if(tab==='equipment')equipPanel();if(tab==='stats')statPanel();if(tab==='skills')skillPanel();if(tab==='details')detailPanel()}
function actualSlot(it){if(it.slot!=='ring')return it.slot;if(!state.equipment.ring1)return'ring1';if(!state.equipment.ring2)return'ring2';return itemScore(state.equipment.ring1)<=itemScore(state.equipment.ring2)?'ring1':'ring2'}
function itemScore(it){if(!it)return 0;return it.baseValue+it.options.reduce((n,o)=>n+o.value*(o.unit==='％'?1.25:.45),0)}
function compareHtml(it){const slot=actualSlot(it),old=state.equipment[slot],diff=itemScore(it)-itemScore(old);if(!old)return'<div class="compare"><span class="up">空き枠に装備できます</span></div>';const cls=diff>0?'up':diff<0?'down':'';return'<div class="compare">比較：'+old.name+' <span class="'+cls+'">'+(diff>=0?'▲ +':'▼ ')+diff.toFixed(1)+'</span></div>'}
function itemCard(it){return'<article class="item-card '+['','magic','rare','epic'][it.options.length]+'"><div class="item-head"><b>'+(it.locked?'🔒 ':'')+it.name+'</b><small>要求Lv '+it.requiredLevel+'</small></div><div class="item-base">'+(SLOTS[it.slot]||'指輪')+'｜'+it.baseStat+' +'+it.baseValue+'｜敵Lv'+it.enemyLevel+'</div><ul class="options">'+(it.options.length?it.options.map(o=>'<li class="'+(o.high?'high':'')+'">'+o.name+'Lv'+o.level+'　+'+o.value+o.unit+'</li>').join(''):'<li>一般オプションなし</li>')+'</ul>'+compareHtml(it)+'<div class="item-actions"><button class="primary" data-equip="'+it.id+'" '+(state.level<it.requiredLevel?'disabled':'')+'>'+(state.level<it.requiredLevel?'Lv不足':'装備')+'</button><button data-lock="'+it.id+'">'+(it.locked?'解除':'保護')+'</button><button data-sell="'+it.id+'" '+(it.locked?'disabled':'')+'>分解</button></div></article>'}
function lootPanel(){let items=[...state.inventory].sort((a,b)=>b.options.length-a.options.length||b.enemyLevel-a.enemyLevel);if(lootFilter==='ready')items=items.filter(i=>state.level>=i.requiredLevel);if(lootFilter==='new')items=items.filter(i=>i.new);const toolbar='<div class="loot-toolbar">'+[['all','すべて'],['ready','装備可能'],['new','新着']].map(x=>'<button class="filter-button '+(lootFilter===x[0]?'active':'')+'" data-filter="'+x[0]+'">'+x[1]+'</button>').join('')+'<button class="filter-button" data-tab-jump="equipment">装着中を見る</button></div>';if(!state.inventory.length){ui.body.innerHTML=toolbar+'<div class="empty">戦利品はまだありません<br>敵を倒すと運に応じて装備が落ちます。</div>';return}ui.body.innerHTML=toolbar+(items.length?'<div class="loot-grid">'+items.map(itemCard).join('')+'</div>':'<div class="empty">この条件の装備はありません</div>')}
function equipPanel(){const d=derived(),summary='<div class="equip-summary"><div><small>攻撃</small><b>'+d.attack.toFixed(0)+'</b></div><div><small>防御</small><b>'+d.defense.toFixed(0)+'</b></div><div><small>HP</small><b>'+d.maxHp+'</b></div><div><small>回避</small><b>'+pct(d.evadeChance)+'</b></div></div>';ui.body.innerHTML='<div class="summary">剣士と戦士の武器は変身時に自動で切替。防具・アクセサリーは共通です。</div>'+summary+'<div class="equipment-layout">'+Object.entries(SLOTS).map(([slot,name])=>{const it=state.equipment[slot],weapon=slot.includes('sword')||slot.includes('warrior');return'<article class="slot-card '+(weapon?'weapon':'')+'"><small>'+name+'</small>'+(it?'<b>'+it.name+'</b><div class="item-base">'+it.baseStat+' +'+it.baseValue+' / '+it.options.length+'OP / 要求Lv'+it.requiredLevel+'</div><ul class="options">'+it.options.slice(0,2).map(o=>'<li>'+o.name+'Lv'+o.level+' +'+o.value+o.unit+'</li>').join('')+'</ul><button data-unequip="'+slot+'">外す</button>':'<div class="slot-empty">未装備</div>')+'</article>'}).join('')+'</div>'}
function statPanel(){ui.body.innerHTML='<div class="summary">レベルごとに4ポイント。能力再振りの書：'+state.statRespec+'個</div><div class="stat-grid">'+Object.entries(STAT).map(x=>'<div class="stat-card"><header><b>'+x[1][0]+'</b><strong>'+state.stats[x[0]]+'</strong></header><small>'+x[1][1]+'</small><button class="action" data-stat="'+x[0]+'" '+(state.statPoints<=0?'disabled':'')+'>＋1</button></div>').join('')+'</div><p><button class="action" data-respec="stats">能力を再振りする</button></p>'}
function skillPanel(){const rows=[['sword1','剣士・三連閃','前方を高速で貫く'],['sword2','剣士・守護の構え','受けるダメージを軽減'],['warrior1','戦士・大旋風','周囲の敵を薙ぎ払う'],['warrior2','戦士・鎧砕き','強打して防御を下げる']];ui.body.innerHTML='<div class="summary">両職どちらへ振っても自由。再振りの書：'+state.skillRespec+'個</div><div class="skill-grid">'+rows.map(x=>'<div class="skill-row"><header><b>'+x[1]+'</b><strong>Lv'+state.skills[x[0]]+'</strong></header><p>'+x[2]+'</p><button class="action primary" data-skill="'+x[0]+'" '+(state.skillPoints<=0?'disabled':'')+'>レベルを上げる</button></div>').join('')+'</div><p><button class="action" data-respec="skills">スキルを再振りする</button></p>'}
function detailPanel(){const d=derived(),vals=[['物理攻撃',d.attack.toFixed(1)],['防御',d.defense.toFixed(1)],['最大HP',d.maxHp],['最大CP',d.maxCp],['命中率',pct(d.hitChance)],['回避率',pct(d.evadeChance)],['致命打率',pct(d.critChance)],['ダブクリ率',pct(d.doubleChance)],['装備ドロップ率',pct(d.dropChance)],['抵抗倍率',Math.min(2,1+(d.wis+d.cha)/1000).toFixed(2)+'倍']];ui.body.innerHTML='<div class="summary">'+FORMS[state.form].name+'の現在値</div><div class="detail-grid">'+vals.map(x=>'<div><small>'+x[0]+'</small><b>'+x[1]+'</b></div>').join('')+'</div>'}
function equip(id){const i=state.inventory.findIndex(x=>x.id===id),it=state.inventory[i];if(!it||state.level<it.requiredLevel)return;const slot=actualSlot(it),old=state.equipment[slot];state.equipment[slot]=it;state.inventory.splice(i,1);if(old)state.inventory.unshift(old);save();render();updateHud()}
function unequip(slot){if(!state.equipment[slot]||state.inventory.length>=20)return;state.inventory.unshift(state.equipment[slot]);delete state.equipment[slot];save();render();updateHud()}
function sell(id){const i=state.inventory.findIndex(x=>x.id===id);if(i<0||state.inventory[i].locked)return;state.gold+=5+state.inventory[i].enemyLevel+state.inventory[i].options.length*8;state.inventory.splice(i,1);save();render();updateHud()}
function respec(type){if(type==='stats'&&state.statRespec>0){state.statRespec--;state.statPoints+=(state.level-1)*4;Object.keys(state.stats).forEach(k=>state.stats[k]=10)}if(type==='skills'&&state.skillRespec>0){state.skillRespec--;state.skillPoints+=Object.values(state.skills).reduce((a,v)=>a+v-1,0);Object.keys(state.skills).forEach(k=>state.skills[k]=1)}save();render();updateHud()}
function heal(){const d=derived();if(!state.potions||world.player.hp>=d.maxHp)return;state.potions--;world.player.hp=Math.min(d.maxHp,world.player.hp+d.maxHp*.45);notice('回復薬を使用',500);save();updateHud()}
async function fullscreen(){const root=document.documentElement;if(document.fullscreenElement)return;try{if(root.requestFullscreen){await root.requestFullscreen({navigationUI:'hide'});if(screen.orientation&&screen.orientation.lock)screen.orientation.lock('landscape').catch(()=>{});return}}catch(e){}notice('Safariの共有ボタンを押し<br><small>「ホーム画面に追加」→ 追加したゲームを開くと全画面になります</small>',5200)}
function setStick(x,y){const r=ui.knob.parentElement.getBoundingClientRect(),dx=x-(r.left+r.width/2),dy=y-(r.top+r.height/2),m=Math.hypot(dx,dy)||1,max=30,k=Math.min(1,max/m),sx=dx*k,sy=dy*k;input.x=Math.abs(sx/max)<.16?0:sx/max;input.y=Math.abs(sy/max)<.16?0:sy/max;ui.knob.style.transform='translate('+sx+'px,'+sy+'px)'}function clearStick(){pointer=null;input.x=0;input.y=0;ui.knob.style.transform='translate(0,0)'}
ui.stick.addEventListener('pointerdown',e=>{pointer=e.pointerId;ui.stick.setPointerCapture(e.pointerId);setStick(e.clientX,e.clientY)});ui.stick.addEventListener('pointermove',e=>{if(e.pointerId===pointer)setStick(e.clientX,e.clientY)});ui.stick.addEventListener('pointerup',clearStick);ui.stick.addEventListener('pointercancel',clearStick);ui.skill1.addEventListener('pointerdown',()=>skill(1));ui.skill2.addEventListener('pointerdown',()=>skill(2));ui.dodge.addEventListener('pointerdown',dodge);ui.transform.addEventListener('pointerdown',transform);$('#healButton').addEventListener('click',heal);$('#fullscreenButton').addEventListener('click',fullscreen);$('#lootButton').addEventListener('click',()=>openPanel('loot','loot'));$('#buildButton').addEventListener('click',()=>openPanel('build','stats'));$('#formBadge').addEventListener('click',()=>openPanel('build','details'));$('#closePanel').addEventListener('click',closePanel);ui.overlay.addEventListener('click',e=>{if(e.target===ui.overlay)closePanel()});ui.tabs.addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(b){tab=b.dataset.tab;render()}});
ui.body.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.filter){lootFilter=b.dataset.filter;lootPanel()}if(b.dataset.tabJump){tab=b.dataset.tabJump;render()}if(b.dataset.equip)equip(b.dataset.equip);if(b.dataset.unequip)unequip(b.dataset.unequip);if(b.dataset.sell)sell(b.dataset.sell);if(b.dataset.lock){const it=state.inventory.find(x=>x.id===b.dataset.lock);if(it){it.locked=!it.locked;save();render()}}if(b.dataset.stat&&state.statPoints){state.stats[b.dataset.stat]++;state.statPoints--;save();render();updateHud()}if(b.dataset.skill&&state.skillPoints){state.skills[b.dataset.skill]++;state.skillPoints--;save();render()}if(b.dataset.respec)respec(b.dataset.respec)});ui.restart.addEventListener('click',()=>{ui.message.classList.add('hidden');ui.restart.classList.add('hidden');reset()});window.addEventListener('resize',resize);if(window.visualViewport)visualViewport.addEventListener('resize',resize);new ResizeObserver(resize).observe(canvas);window.addEventListener('orientationchange',()=>{clearStick();[80,320,800].forEach(ms=>setTimeout(resize,ms))});document.addEventListener('visibilitychange',()=>{world.paused=document.hidden||!ui.overlay.classList.contains('hidden');if(document.hidden)save()});
function weighted(a){let total=a.reduce((s,x)=>s+x[3],0),r=Math.random()*total;for(const x of a){r-=x[3];if(r<=0)return x}return a[a.length-1]}function pick(a){return a[Math.floor(Math.random()*a.length)]}function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function delta(a,b){return Math.atan2(Math.sin(a-b),Math.cos(a-b))}function pct(v){return(v*100).toFixed(1)+'％'}function frame(n){const dt=Math.min(.034,(n-last)/1000);last=n;update(dt);draw();requestAnimationFrame(frame)}
state=load();reset();if(navigator.standalone)$('#fullscreenButton').classList.add('hidden');requestAnimationFrame(frame);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
