import test from 'node:test';import assert from 'node:assert/strict';
import {makeState,createMonster,startRift,riftLayout,enterRiftWalk,moveRiftWalk,collectRiftChest,riftAtExit,riftEncounter,act,validState,validBattle} from '../dist/engine.js';
const cleared=seed=>{const s=makeState();s.seed=seed;s.ended=true;s.badges=[0,1,2,3];s.party=[0,2,5,7,12,15].map(id=>createMonster(id,40));startRift(s);enterRiftWalk(s);return s;};
function route(map,start,target){const queue=[{...start,path:[]}],seen=new Set([`${start.x},${start.y}`]);for(let i=0;i<queue.length;i++){const p=queue[i];if(p.x===target.x&&p.y===target.y)return p.path;for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const key=`${p.x+dx},${p.y+dy}`;if(map.cells[p.y+dy]?.[p.x+dx]&&!seen.has(key)){seen.add(key);queue.push({x:p.x+dx,y:p.y+dy,path:[...p.path,[dx,dy]]});}}}return null;}
test('500 seeded labyrinths are connected, deterministic and have distant exits and reachable treasure',()=>{const signatures=new Set();for(let seed=1;seed<=100;seed++)for(let floor=1;floor<=5;floor++){const run={seed,floor},map=riftLayout(run);assert.deepEqual(map,riftLayout(JSON.parse(JSON.stringify(run))));assert.ok(map.exit.d>20);assert.ok(map.chests.length>=1&&map.chests.length<=2);const passable=map.cells.flat().filter(Boolean).length;assert.equal(passable,95);for(let y=0;y<map.height;y++)for(let x=0;x<map.width;x++)if(map.cells[y][x])assert.ok(route(map,{x:1,y:1},{x,y}));for(const chest of map.chests)assert.ok(route(map,{x:1,y:1},chest));signatures.add(JSON.stringify(map.cells));}assert.equal(signatures.size,500);});
test('walking, wall collision, chest reward and exact position persist without changing island coordinates',()=>{let s=cleared(7);const run=s.postgame.rift,map=riftLayout(run),island=[s.x,s.y,s.steps];assert.equal(moveRiftWalk(s,-1,0),false);const chest=map.chests[0];for(const [dx,dy]of route(map,run.walk,chest))assert.ok(moveRiftWalk(s,dx,dy));const before=run.pending;assert.ok(collectRiftChest(s));assert.equal(run.pending,before+2);assert.equal(collectRiftChest(s),false);s=JSON.parse(JSON.stringify(s));assert.ok(validState(s));assert.equal(collectRiftChest(s),false);assert.deepEqual([s.x,s.y,s.steps],island);for(const [dx,dy]of route(map,s.postgame.rift.walk,map.exit))assert.ok(moveRiftWalk(s,dx,dy));assert.ok(riftAtExit(s));assert.ok(validState(s));});
test('battle advances to a fresh saved floor and walking is blocked during combat',()=>{const s=cleared(1),b=riftEncounter(s);assert.equal(moveRiftWalk(s,1,0),false);assert.equal(collectRiftChest(s),false);let turns=0;while(!b.result&&turns++<200)act(s,b,'attack');assert.equal(b.result,'win');assert.deepEqual(s.postgame.rift.walk,{floor:2,x:1,y:1,opened:[],triggered:[]});assert.ok(validState(s));assert.ok(validBattle(b,s));assert.ok(validBattle(null,s));});
test('every labyrinth has three distinct one-shot terrain effects that survive reload',()=>{for(let seed=1;seed<=100;seed++){const s=cleared(seed),run=s.postgame.rift,map=riftLayout(run);assert.deepEqual(map.terrains.map(p=>p.type).sort(),['moss','thorns','vein']);assert.equal(new Set(map.terrains.map(p=>`${p.x},${p.y}`)).size,3);for(const p of map.terrains){assert.ok(map.cells[p.y][p.x]);assert.notDeepEqual([p.x,p.y],[1,1]);assert.notDeepEqual([p.x,p.y],[map.exit.x,map.exit.y]);}}
 for(const type of ['moss','vein','thorns']){let s=cleared(77),run=s.postgame.rift,map=riftLayout(run),p=map.terrains.find(v=>v.type===type),neighbor=[[1,0],[-1,0],[0,1],[0,-1]].map(([dx,dy])=>({x:p.x-dx,y:p.y-dy,dx,dy})).find(n=>map.cells[n.y]?.[n.x]&&!map.terrains.some(t=>t.x===n.x&&t.y===n.y));run.walk.x=neighbor.x;run.walk.y=neighbor.y;const before={potions:s.potions,pending:run.pending,hp:s.party.map(m=>m.hp)};assert.ok(moveRiftWalk(s,neighbor.dx,neighbor.dy));assert.deepEqual(run.walk.triggered,[`${p.x},${p.y}`]);if(type==='moss')assert.equal(s.potions,before.potions+1);if(type==='vein')assert.equal(run.pending,before.pending+1);if(type==='thorns')assert.deepEqual(s.party.map(m=>m.hp),[before.hp[0]-5,...before.hp.slice(1)]);assert.ok(moveRiftWalk(s,-neighbor.dx,-neighbor.dy));assert.ok(moveRiftWalk(s,neighbor.dx,neighbor.dy));if(type==='moss')assert.equal(s.potions,before.potions+1);if(type==='vein')assert.equal(run.pending,before.pending+1);if(type==='thorns')assert.deepEqual(s.party.map(m=>m.hp),[before.hp[0]-5,...before.hp.slice(1)]);s=JSON.parse(JSON.stringify(s));assert.ok(validState(s));}
});
test('legacy room-based saves remain valid and malformed walking saves are rejected',()=>{const s=cleared(9);delete s.postgame.rift.walk;assert.ok(validState(s));assert.ok(enterRiftWalk(s));const good=JSON.parse(JSON.stringify(s)),terrain=`${riftLayout(good.postgame.rift).terrains[0].x},${riftLayout(good.postgame.rift).terrains[0].y}`;const legacy=JSON.parse(JSON.stringify(good));delete legacy.postgame.rift.walk.triggered;assert.ok(validState(legacy));assert.ok(moveRiftWalk(legacy,1,0)||moveRiftWalk(legacy,0,1));for(const walk of [{floor:1,x:0,y:0,opened:[],triggered:[]},{floor:2,x:1,y:1,opened:[],triggered:[]},{floor:1,x:1,y:1,opened:[0,0],triggered:[]},{floor:1,x:1,y:1,opened:[99],triggered:[]},{floor:1,x:1,y:1,opened:[],triggered:[terrain,terrain]},{floor:1,x:1,y:1,opened:[],triggered:['99,99']}]){const bad=JSON.parse(JSON.stringify(good));bad.postgame.rift.walk=walk;assert.equal(validState(bad),false);}});
