import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';import * as engine from '../dist/engine.js';
// DOM contract harness: executes production UI handlers without a browser runtime.
function boot(saved,backup,soundPref,prefs={}){const nodes=new Map(),timers=[];const storage=new Map();if(saved!==undefined&&saved!==null)storage.set('lumina-save-v1',typeof saved==='string'?saved:JSON.stringify(saved));if(backup!==undefined&&backup!==null)storage.set('lumina-save-v1-backup',typeof backup==='string'?backup:JSON.stringify(backup));if(soundPref)storage.set('lumina-sound-v1',soundPref);for(const[k,v]of Object.entries(prefs))storage.set(k,v);
class Element{constructor(tag='DIV',attrs={}){this.tagName=tag.toUpperCase();this.attrs=attrs;this.dataset={};this.children=[];this.style={};this.listeners={};this.className='';this.classList={add:()=>{},remove:()=>{}};for(const [k,v]of Object.entries(attrs))if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=v;this.id=attrs.id;if(this.id)nodes.set(this.id,this);}set innerHTML(html){this.html=html;for(const c of this.children)if(c.id)nodes.delete(c.id);this.children=[];for(const match of html.matchAll(/<([a-zA-Z]+)\b([^>]*)>/g)){const attrs={};for(const a of match[2].matchAll(/([\w-]+)="([^"]*)"/g))attrs[a[1]]=a[2];if(/\bdisabled\b/.test(match[2]))attrs.disabled=true;const el=new Element(match[1],attrs);el.disabled=attrs.disabled;this.children.push(el);}}get innerHTML(){return this.html;}querySelectorAll(sel){const a=sel.match(/^\[([^\]]+)\]$/)?.[1];return this.children.filter(c=>a&&Object.hasOwn(c.attrs,a));}addEventListener(event,fn){this.listeners[event]=fn;}setPointerCapture(){}click(){if(!this.disabled)this.onclick?.({target:this,preventDefault(){}});}getContext(){return new Proxy({},{get:(_,k)=>()=>{}});}getBoundingClientRect(){return {width:390,height:390};}}
const doc=new Element();doc.innerHTML=fs.readFileSync('dist/index.html','utf8');doc.getElementById=id=>nodes.get(id);doc.hidden=false;doc.createElement=tag=>new Element(tag);doc.querySelectorAll=Element.prototype.querySelectorAll.bind(doc);const noop=()=>{};
class FakeAudio{constructor(src){this.src=src;}play(){return Promise.resolve();}pause(){}}
const context={...engine,document:doc,window:{addEventListener:noop},navigator:{},Image:class{constructor(){this.complete=false;}},Audio:FakeAudio,localStorage:{getItem:key=>storage.get(key)??null,setItem:(key,val)=>storage.set(key,val)},setTimeout:(fn)=>{timers.push(fn);return 1;},clearTimeout:noop,setInterval:()=>1,clearInterval:noop,console,Date,Math,JSON,Number,Object,Array,URL,Blob};vm.createContext(context);const code=fs.readFileSync('dist/game.js','utf8').replace(/^import[^\n]+\n/,'');vm.runInContext(code,context);return {nodes,scene:()=>nodes.get('scene'),read:()=>JSON.parse(storage.get('lumina-save-v1')),backup:()=>storage.get('lumina-save-v1-backup'),stored:key=>storage.get(key),click:id=>{assert.ok(nodes.get(id),id+' exists');nodes.get(id).click();},data:(key)=>nodes.get('scene').querySelectorAll('['+key+']'),flush:()=>{while(timers.length)timers.shift()();},context};}
test('new game starter, menu, codex, bag and map render using actual UI handlers',()=>{const ui=boot();assert.equal(ui.data('data-starter').length,3);ui.data('data-starter')[0].click();assert.ok(engine.validState(ui.read().state));ui.click('menu');assert.ok(ui.scene().innerHTML.includes('セーブを書き出す'));ui.click('closeModal');ui.click('dexBtn');assert.equal(ui.data('data-dex').length,56);ui.click('closeModal');ui.click('partyBtn');assert.equal(ui.data('data-lead').length,1);ui.click('closeModal');ui.click('bagBtn');assert.ok(ui.scene().innerHTML.includes('捕獲クリスタル'));ui.click('closeModal');ui.click('mapBtn');assert.equal(ui.data('data-travel').length,4);assert.ok(ui.data('data-travel')[1].disabled);});
test('new species use the second sprite sheet in codex and battle views',()=>{const s=engine.makeState();s.caught.push(23);s.seen.push(23);s.party=[engine.createMonster(23,20)];let ui=boot({state:s,battle:null});ui.click('dexBtn');ui.data('data-dex').find(el=>el.dataset.dex==='23').click();assert.ok(ui.scene().innerHTML.includes('sprite extra'));const b=engine.encounter(s,3);b.enemy=engine.createMonster(22,20);ui=boot({state:s,battle:b});assert.ok(ui.scene().innerHTML.includes('sprite extra'));});
test('third species sheet and habitat guidance render through production UI',()=>{const s=engine.makeState();s.caught.push(31);s.seen.push(31);s.party=[engine.createMonster(31,20)];let ui=boot({state:s,battle:null});ui.click('dexBtn');assert.equal(ui.data('data-dex').length,56);ui.data('data-dex').find(el=>el.dataset.dex==='31').click();assert.ok(ui.scene().innerHTML.includes('sprite extra2'));assert.ok(ui.scene().innerHTML.includes('生息地：星影の森'));const b=engine.encounter(s,3);b.enemy=engine.createMonster(30,20);ui=boot({state:s,battle:b});assert.ok(ui.scene().innerHTML.includes('sprite extra2'));});
test('fourth species sheet and habitat guidance render through production UI',()=>{const s=engine.makeState();s.caught.push(39);s.seen.push(39);s.party=[engine.createMonster(39,20)];let ui=boot({state:s,battle:null});ui.click('dexBtn');assert.equal(ui.data('data-dex').length,56);ui.data('data-dex').find(el=>el.dataset.dex==='39').click();assert.ok(ui.scene().innerHTML.includes('sprite extra3'));assert.ok(ui.scene().innerHTML.includes('生息地：星影の森'));const b=engine.encounter(s,3);b.enemy=engine.createMonster(38,20);ui=boot({state:s,battle:b});assert.ok(ui.scene().innerHTML.includes('sprite extra3'));});
test('fifth species sheet uses five columns and renders the fiftieth habitat',()=>{const s=engine.makeState();s.caught.push(49);s.seen.push(49);s.party=[engine.createMonster(49,20)];let ui=boot({state:s,battle:null});ui.click('dexBtn');assert.equal(ui.data('data-dex').length,56);ui.data('data-dex').find(el=>el.dataset.dex==='49').click();assert.ok(ui.scene().innerHTML.includes('sprite extra4'));assert.ok(ui.scene().innerHTML.includes('background-position:100% 100%'));assert.ok(ui.scene().innerHTML.includes('生息地：星影の森'));const b=engine.encounter(s,3);b.enemy=engine.createMonster(48,20);ui=boot({state:s,battle:b});assert.ok(ui.scene().innerHTML.includes('sprite extra4'));});
test('sixth species sheet renders the rift-only habitat and final sprite cell',()=>{const s=engine.makeState();s.caught.push(55);s.seen.push(55);s.party=[engine.createMonster(55,20)];let ui=boot({state:s,battle:null});ui.click('dexBtn');assert.equal(ui.data('data-dex').length,56);ui.data('data-dex').find(el=>el.dataset.dex==='55').click();assert.ok(ui.scene().innerHTML.includes('sprite extra5'));assert.ok(ui.scene().innerHTML.includes('background-position:100% 100%'));assert.ok(ui.scene().innerHTML.includes('生息地：夢の裂け目・深層'));});
test('healer and shop transactions, persistence and reload',()=>{const s=engine.makeState();s.x=7;s.y=8;s.party[0].hp=1;let ui=boot({state:s,battle:null});ui.click('interact');assert.equal(ui.read().state.party[0].hp,engine.maxHP(s.party[0]));const saved=ui.read();saved.state.x=10;saved.state.y=8;ui=boot(saved);ui.click('interact');ui.click('buyBalls');assert.equal(ui.read().state.coins,50);assert.equal(ui.read().state.balls,17);assert.ok(engine.validState(ui.read().state));const ui2=boot(ui.read());assert.equal(ui2.read().state.balls,17);});
test('actual battle handlers resume save, attack, victory and ending return',()=>{const s=engine.makeState();s.party=[engine.createMonster(4,35),engine.createMonster(6,35)];s.badges=[0,1,2,3];const b=engine.encounter(s,3,true,true);let ui=boot({state:s,battle:b});let turns=0;while(!ui.read().battle.result&&turns++<40){ui.data('data-action').find(x=>x.dataset.action==='attack').click();ui.flush();}assert.equal(ui.read().battle.result,'win');assert.equal(ui.read().state.ended,true);ui.click('endBattle');assert.ok(ui.scene().innerHTML.includes('ルミナ島に光が戻った'));ui.click('postgame');assert.equal(ui.scene().className,'scene');assert.equal(ui.read().battle,null);});
test('party switch does not let a battle escape through closing a modal',()=>{const s=engine.makeState();s.party.push(engine.createMonster(2,5));const b=engine.encounter(s,0);const ui=boot({state:s,battle:b});ui.click('battleSwitch');ui.click('closeModal');assert.ok(ui.scene().innerHTML.includes('battle-actions'));ui.click('battleSwitch');ui.data('data-switch')[1].click();ui.flush();assert.equal(ui.read().battle.active,1);assert.equal(ui.read().battle.turn,1);});
test('corrupt current save restores backup and repairs current without overwriting backup',()=>{const s=engine.makeState(2);s.coins=777;const backup=JSON.stringify({state:s,battle:null});const ui=boot('{broken-json',backup);assert.equal(ui.read().state.coins,777);assert.equal(ui.read().state.party[0].id,2);assert.equal(ui.backup(),backup);});
test('unreadable saves block silent restart and keep both originals',()=>{const ui=boot('{broken-json','bad-backup');assert.ok(ui.scene().innerHTML.includes('セーブの復旧'));assert.equal(ui.data('data-starter').length,0);assert.equal(ui.stored('lumina-save-v1'),'{broken-json');assert.equal(ui.backup(),'bad-backup');ui.click('recoverNew');assert.ok(ui.stored('lumina-save-v1-recovery').includes('broken-json'));ui.data('data-starter')[0].click();assert.equal(ui.read().state.party[0].level,1);assert.ok(ui.stored('lumina-save-v1-recovery').includes('bad-backup'));});
test('missing primary restores a valid backup rather than selecting a new starter',()=>{const s=engine.makeState(1);s.coins=888;const ui=boot(null,{state:s,battle:null});assert.equal(ui.read().state.coins,888);assert.equal(ui.data('data-starter').length,0);});
test('journey guide explains preparation and invalid runtime saves cannot overwrite a good save',()=>{const s=engine.makeState();s.playSeconds=185;const ui=boot({state:s,battle:null});ui.click('menu');ui.click('journeyGuide');assert.ok(ui.scene().innerHTML.includes('Lv.23〜25'));assert.ok(ui.scene().innerHTML.includes('診療所は無料'));assert.ok(ui.scene().innerHTML.includes('現在の成長バランス'));assert.ok(ui.scene().innerHTML.includes('章別プレイ時間'));assert.ok(ui.scene().innerHTML.includes('0時間3分（進行中）'));const previous=ui.stored('lumina-save-v1');vm.runInContext('state.party[0].hp=99999;save()',ui.context);assert.equal(ui.stored('lumina-save-v1'),previous);assert.equal(ui.nodes.get('saveStatus').textContent,'保存を保留');});
test('broken battle preserves valid adventure and quarantines original record',()=>{const s=engine.makeState();s.badges=[0,1];s.party=[engine.createMonster(4,13)];s.coins=999;const b=engine.encounter(s,2);b.enemy.hp=99999;const raw=JSON.stringify({state:s,battle:b});const ui=boot(raw);assert.equal(ui.read().state.coins,999);assert.deepEqual(ui.read().state.badges,[0,1]);assert.equal(ui.read().state.party[0].level,13);assert.equal(ui.read().battle,null);assert.equal(ui.stored('lumina-save-v1-recovery'),raw);});
test('sound preference survives reload and a direct tap unlocks playback',async()=>{const ui=boot(null,null,'on');assert.equal(ui.nodes.get('sound').textContent,'音 再開');ui.click('sound');assert.equal(ui.stored('lumina-sound-v1'),'off');ui.click('sound');assert.equal(ui.stored('lumina-sound-v1'),'on');await Promise.resolve();assert.equal(ui.nodes.get('sound').textContent,'音 ON');});
test('each guardian presents its own tactical dialogue before battle',()=>{for(let r=0;r<4;r++){const s=engine.makeState();s.badges=Array.from({length:r},(_,i)=>i);s.x=[13,39,14,39][r];s.y=[8,14,28,30][r];s.region=r;const ui=boot({state:s,battle:null});ui.click('interact');assert.ok(ui.scene().innerHTML.includes(engine.REGIONS[r].challenge),`guardian ${r}`);assert.ok(ui.nodes.get('challenge'));}});
test('canvas swipe moves exactly one tile using production pointer handlers',()=>{const s=engine.makeState();s.x=8;s.y=10;const ui=boot({state:s,battle:null}),canvas=ui.nodes.get('world');canvas.listeners.pointerdown({pointerId:7,clientX:80,clientY:100});canvas.listeners.pointerup({pointerId:7,clientX:140,clientY:102,preventDefault(){}});assert.equal(ui.read().state.x,9);assert.equal(ui.read().state.y,10);assert.equal(ui.read().state.steps,1);});
test('all four movement directions face correctly, including blocked moves and reload',()=>{
 for(const [dx,dy,dir] of [[0,-1,0],[1,0,1],[0,1,2],[-1,0,3]]){
  const s=engine.makeState();s.x=8;s.y=10;const ui=boot({state:s,battle:null});vm.runInContext(`move(${dx},${dy})`,ui.context);
  assert.equal(ui.read().state.dir,dir);assert.equal(vm.runInContext('state.dir',boot(ui.read()).context),dir);
 }
 const s=engine.makeState();s.x=7;s.y=8;const ui=boot({state:s,battle:null});vm.runInContext('move(0,-1)',ui.context);
 assert.equal(ui.read().state.y,8);assert.equal(ui.read().state.steps,0);assert.equal(ui.read().state.dir,0);
});
test('stick rotates while held, ignores a second pointer, and stops on release',()=>{
 const s=engine.makeState();s.x=8;s.y=10;const ui=boot({state:s,battle:null}),stick=ui.nodes.get('joystick');
 stick.getBoundingClientRect=()=>({left:0,top:0,width:136,height:136});
 const event=(id,x,y)=>({pointerId:id,clientX:x,clientY:y,preventDefault(){}});
 stick.listeners.pointerdown(event(1,120,68));assert.equal(ui.read().state.x,9);
 stick.listeners.pointermove(event(2,68,120));assert.equal(vm.runInContext('stickDir[0]',ui.context),1);
 stick.listeners.pointermove(event(1,68,120));vm.runInContext('movedAt=0;tickStick()',ui.context);
 assert.equal(ui.read().state.x,9);assert.equal(ui.read().state.y,11);
 stick.listeners.pointerup(event(1,68,120));vm.runInContext('movedAt=0;tickStick()',ui.context);
 assert.equal(ui.read().state.steps,2);assert.equal(ui.nodes.get('stickKnob').style.transform,'translate(0px, 0px)');
});
test('stick dead zone, pointer cancel and hidden-page handling stop movement',()=>{
 const s=engine.makeState();s.x=8;s.y=10;const ui=boot({state:s,battle:null}),stick=ui.nodes.get('joystick');
 stick.getBoundingClientRect=()=>({left:0,top:0,width:136,height:136});
 const e=(x,y)=>({pointerId:1,clientX:x,clientY:y,preventDefault(){}});
 stick.listeners.pointerdown(e(70,70));vm.runInContext('movedAt=0;tickStick()',ui.context);assert.equal(ui.read().state.steps,0);
 stick.listeners.pointermove(e(300,68));assert.match(ui.nodes.get('stickKnob').style.transform,/43\.52px/);
 stick.listeners.pointercancel(e(300,68));assert.equal(vm.runInContext('stickPointer',ui.context),null);
 stick.listeners.pointerdown(e(120,68));ui.context.document.hidden=true;ui.context.document.listeners.visibilitychange();
 assert.equal(vm.runInContext('stickPointer',ui.context),null);
});
test('zoom and controller preferences persist without changing the game save',()=>{
 const s=engine.makeState();const ui=boot({state:s,battle:null});
 assert.equal(ui.nodes.get('zoomBtn').textContent,'拡大 1.5×');assert.equal(ui.nodes.get('joystick').hidden,false);
 ui.click('zoomBtn');ui.click('controlMode');assert.equal(ui.stored('lumina-zoom-v1'),'1');assert.equal(ui.stored('lumina-control-v1'),'dpad');
 assert.equal(ui.nodes.get('joystick').hidden,true);assert.ok(ui.context.document.querySelectorAll('[data-dir]').every(el=>!el.hidden));
 const resumed=boot(ui.read(),null,null,{'lumina-zoom-v1':'1','lumina-control-v1':'dpad'});
 assert.equal(resumed.nodes.get('zoomBtn').textContent,'拡大 1×');assert.equal(resumed.nodes.get('joystick').hidden,true);assert.equal(resumed.read().state.party[0].id,s.party[0].id);
});
test('landscape layout defines side controls, safe areas, full-screen dialogs and cross-shaped dpad',()=>{
 const css=fs.readFileSync('dist/style.css','utf8');assert.match(css,/@media\(orientation:landscape\)/);assert.match(css,/grid-template-columns:150px minmax\(0,1fr\) 146px/);
 assert.match(css,/\.dpad \[data-dir=down\]\{[^}]*grid-row:3/);assert.match(css,/\.scene\{position:fixed/);
 assert.match(fs.readFileSync('dist/game.js','utf8'),/ctx.setTransform\(mapZoom,0,0,mapZoom,0,0\)/);
});
test('learned technique equipment and battle move selection persist via actual handlers',()=>{
 const s=engine.makeState();s.party=[engine.createMonster(0,28)];let ui=boot({state:s,battle:null});ui.click('partyBtn');ui.data('data-tech')[0].click();
 assert.equal(ui.data('data-learned').length,8);ui.data('data-learned').find(el=>el.dataset.learned==='2').click();ui.data('data-slot')[0].click();assert.equal(ui.read().state.party[0].moves[0],2);
 const saved=ui.read(),b=engine.encounter(saved.state,0);saved.state.party[0].hp-=50;ui=boot({state:saved.state,battle:b});ui.click('battleMoves');
 assert.equal(ui.data('data-move').length,4);ui.data('data-move').find(el=>el.dataset.move==='2').click();ui.flush();assert.equal(ui.read().battle.turn,1);assert.ok(ui.read().battle.log.some(x=>x.includes('芽吹きの祈り')));
 const resumed=boot(ui.read());assert.equal(resumed.read().state.party[0].moves[0],2);assert.ok(resumed.scene().innerHTML.includes('battle-actions'));
});
test('a legacy save immediately migrates move slots and preserves its backup',()=>{
 const s=engine.makeState();s.party[0]=engine.createMonster(0,3);delete s.growthVersion;delete s.party[0].moves;delete s.postgame;const raw=JSON.stringify({state:s,battle:null}),ui=boot(raw,raw);
 assert.deepEqual(ui.read().state.party[0].moves,[0,1]);assert.deepEqual(ui.read().state.postgame,{medals:0,bestFloor:0,runs:0,tower:null,riftBest:0,riftRuns:0,rift:null,guardianRanks:[0,0,0,0],guardianWins:0});assert.equal(ui.backup(),raw);
});
test('cleared save starts an enhanced guardian stage from the map and keeps the record after reload',()=>{const s=engine.makeState();s.ended=true;s.badges=[0,1,2,3];s.x=13;s.y=8;s.region=0;s.party=Array.from({length:6},(_,i)=>engine.createMonster([1,5,12,13,14,15][i],40,false,{vitality:3,force:3},0));let ui=boot({state:s,battle:null});ui.click('interact');assert.ok(ui.scene().innerHTML.includes('強化戦 最高第0段階'));ui.click('masterRematch');assert.equal(ui.read().battle.master,true);assert.equal(ui.read().battle.masterRank,1);for(const foe of [ui.read().battle.enemy,...ui.read().battle.roster])foe.hp=1;let turns=0;while(!ui.read().battle.result&&turns++<20){ui.data('data-action').find(x=>x.dataset.action==='attack').click();ui.flush();}assert.equal(ui.read().battle.result,'win');assert.equal(ui.read().state.postgame.guardianRanks[0],1);ui.click('endBattle');ui=boot(ui.read());assert.equal(ui.read().state.postgame.guardianRanks[0],1);});
test('cleared save enters tower, wins, banks rewards and resumes them through actual UI',()=>{
 const s=engine.makeState();s.ended=true;s.badges=[0,1,2,3];s.party=Array.from({length:6},(_,i)=>engine.createMonster(i<4?i:i+8,40));let ui=boot({state:s,battle:null});
 ui.click('menu');ui.click('towerBtn');assert.ok(ui.scene().innerHTML.includes('研究メダル'));ui.click('towerStart');assert.equal(ui.read().battle.towerFloor,1);
 let turns=0;while(!ui.read().battle.result&&turns++<80){ui.data('data-action').find(x=>x.dataset.action==='attack').click();ui.flush();}
 assert.equal(ui.read().battle.result,'win');ui.click('endBattle');assert.ok(ui.scene().innerHTML.includes('未確定 2枚'));ui.click('towerRetire');
 assert.equal(ui.read().state.postgame.medals,2);assert.equal(ui.read().state.postgame.runs,1);assert.equal(ui.read().state.postgame.tower,null);
 ui=boot(ui.read());ui.click('menu');ui.click('towerBtn');assert.ok(ui.scene().innerHTML.includes('研究メダル 2枚'));
});
test('party shows traits and nature effects while both research choices persist through actual UI',()=>{
 const s=engine.makeState();s.ended=true;s.badges=[0,1,2,3];s.postgame.medals=16;s.party[0].aptitudes={vitality:0,force:2};s.party[0].nature=0;s.party[0].hp=engine.maxHP(s.party[0]);let ui=boot({state:s,battle:null});
 ui.click('partyBtn');assert.ok(ui.scene().innerHTML.includes('個性：勇猛'));assert.ok(ui.scene().innerHTML.includes('性格：勇敢'));assert.ok(ui.scene().innerHTML.includes('与えるダメージ +8%'));assert.ok(ui.scene().innerHTML.includes('生命 ◇◇◇'));
 ui.click('closeModal');ui.click('menu');ui.click('towerBtn');ui.click('researchNature');assert.equal(ui.read().state.party[0].nature,1);assert.equal(ui.read().state.postgame.medals,10);assert.ok(ui.scene().innerHTML.includes('慎重'));ui.click('researchTrain');assert.equal(ui.read().state.party[0].aptitudes.vitality,1);assert.equal(ui.read().state.postgame.medals,0);assert.ok(ui.scene().innerHTML.includes('生命か力の低い方を強化'));ui=boot(ui.read());ui.click('partyBtn');assert.ok(ui.scene().innerHTML.includes('性格：慎重'));
});
test('dex research claims, repeating capture survey and training survive UI reload',()=>{
 const s=engine.makeState();s.ended=true;s.badges=[0,1,2,3];s.caught=[0,1,2,4];s.captures=10;let ui=boot({state:s,battle:null});
 ui.click('dexBtn');ui.click('dexResearch');ui.data('data-research').find(el=>el.dataset.research==='dex-4').click();assert.equal(ui.read().state.postgame.medals,5);
 ui.data('data-research').find(el=>el.dataset.research==='type-0').click();ui.click('captureResearch');assert.equal(ui.read().state.postgame.medals,16);assert.equal(ui.read().state.balls,14);
 ui=boot(ui.read());ui.click('dexBtn');ui.click('dexResearch');assert.ok(ui.data('data-research').find(el=>el.dataset.research==='dex-4').disabled);assert.ok(ui.nodes.get('captureResearch').disabled);
 ui.click('researchExchange');ui.click('researchTrain');assert.equal(ui.read().state.postgame.medals,6);assert.equal(ui.read().state.party[0].aptitudes.vitality,2);
});
test('cleared save explores a seeded rift, resumes after battle and banks rewards via UI',()=>{
 const s=engine.makeState();s.seed=321;s.ended=true;s.badges=[0,1,2,3];s.party=Array.from({length:6},(_,i)=>engine.createMonster(i<4?i:i+8,40));let ui=boot({state:s,battle:null});
 ui.click('menu');ui.click('riftBtn');assert.ok(ui.scene().innerHTML.includes('5〜15層'));ui.click('riftStart');assert.equal(ui.scene().className,'scene');const saved=ui.read(),map=engine.riftLayout(saved.state.postgame.rift),queue=[{x:1,y:1,path:[]}],seen=new Set(['1,1']);let path;
 for(let i=0;i<queue.length;i++){const p=queue[i];if(p.x===map.exit.x&&p.y===map.exit.y){path=p.path;break;}for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const key=`${p.x+dx},${p.y+dy}`;if(map.cells[p.y+dy]?.[p.x+dx]&&!seen.has(key)){seen.add(key);queue.push({x:p.x+dx,y:p.y+dy,path:[...p.path,[dx,dy]]});}}}assert.ok(path.length>5);
 for(const [dx,dy]of path)vm.runInContext(`movedAt=0;move(${dx},${dy})`,ui.context);assert.ok(engine.riftAtExit(ui.read().state));ui=boot(ui.read());assert.ok(engine.riftAtExit(ui.read().state));ui.click('interact');assert.ok(ui.scene().innerHTML.includes('揺らぐ獣道'));ui.click('riftBattle');assert.equal(ui.read().battle.riftFloor,1);
 let turns=0;while(!ui.read().battle.result&&turns++<80){ui.data('data-action').find(x=>x.dataset.action==='attack').click();ui.flush();}
 assert.equal(ui.read().battle.result,'win');ui.click('endBattle');assert.ok(ui.scene().innerHTML.includes('未確定'));ui.click('riftRetire');
 assert.equal(ui.read().state.postgame.rift,null);assert.equal(ui.read().state.postgame.riftRuns,1);assert.ok(ui.read().state.postgame.medals>=2);
 ui=boot(ui.read());ui.click('menu');ui.click('riftBtn');assert.ok(ui.scene().innerHTML.includes('帰還 1回'));
});
test('walking rift chest uses the interaction handler once and stays collected after reload',()=>{const s=engine.makeState();s.ended=true;s.badges=[0,1,2,3];engine.startRift(s);engine.enterRiftWalk(s);const chest=engine.riftLayout(s.postgame.rift).chests[0];s.postgame.rift.walk.x=chest.x;s.postgame.rift.walk.y=chest.y;let ui=boot({state:s,battle:null});assert.equal(ui.nodes.get('mapBtn').textContent,'探索記録');ui.click('interact');assert.equal(ui.read().state.postgame.rift.pending,2);assert.deepEqual(ui.read().state.postgame.rift.walk.opened,[0]);ui.click('interact');assert.equal(ui.read().state.postgame.rift.pending,2);ui=boot(ui.read());ui.click('interact');assert.equal(ui.read().state.postgame.rift.pending,2);ui.click('mapBtn');assert.ok(ui.nodes.get('riftExplore'));assert.equal(ui.nodes.get('riftBattle'),undefined);ui.click('riftExplore');assert.equal(ui.scene().className,'scene');});
test('rift terrain uses production movement feedback and persists its one-shot result',()=>{const s=engine.makeState();s.seed=77;s.ended=true;s.badges=[0,1,2,3];engine.startRift(s);engine.enterRiftWalk(s);const run=s.postgame.rift,map=engine.riftLayout(run),p=map.terrains.find(v=>v.type==='vein'),n=[[1,0],[-1,0],[0,1],[0,-1]].map(([dx,dy])=>({x:p.x-dx,y:p.y-dy,dx,dy})).find(v=>map.cells[v.y]?.[v.x]);run.walk.x=n.x;run.walk.y=n.y;const pending=run.pending,ui=boot({state:s,battle:null});vm.runInContext(`move(${n.dx},${n.dy})`,ui.context);assert.equal(ui.read().state.postgame.rift.pending,pending+1);assert.equal(ui.nodes.get('toast').textContent,'星脈を発見！ 未確定メダル +1');assert.deepEqual(ui.read().state.postgame.rift.walk.triggered,[`${p.x},${p.y}`]);const resumed=boot(ui.read());assert.deepEqual(resumed.read().state.postgame.rift.walk.triggered,[`${p.x},${p.y}`]);});
test('elder advances the first two story chapters and the objective survives reload',()=>{
 const s=engine.makeState();s.x=8;s.y=5;let ui=boot({state:s,battle:null});
 assert.match(ui.nodes.get('objective').textContent,/第1章/);
 ui.click('interact');assert.ok(ui.scene().innerHTML.includes('消えた森の足音'));
 ui.click('storyClose');vm.runInContext('state.captures++;save();update()',ui.context);
 assert.match(ui.nodes.get('objective').textContent,/報告/);
 ui.click('interact');assert.ok(ui.scene().innerHTML.includes('第1章　完了'));
 assert.equal(ui.read().state.campaign.chapter,2);
 ui.click('storyClose');vm.runInContext('state.wins+=3;save();update()',ui.context);
 ui.click('interact');assert.ok(ui.scene().innerHTML.includes('若葉の紋章'));
 ui.click('storyClose');vm.runInContext('state.badges.push(0);save();update()',ui.context);
 ui.click('interact');assert.ok(ui.scene().innerHTML.includes('第2章　完了'));
 assert.equal(ui.read().state.campaign.chapter,3);
 ui=boot(ui.read());assert.equal(ui.read().state.campaign.chapter,3);assert.ok(engine.validState(ui.read().state));
});
test('shore clues are inspected through production UI and stay collected after reload',()=>{
 const s=engine.makeState();s.badges=[0];s.region=1;s.campaign={schema:2,chapter:3,step:1,baseWins:4,baseCaptures:2,claimed:[1,2],discoveries:[]};let ui=boot({state:s,battle:null});
 for(let i=0;i<engine.SHORE_CLUES.length;i++){const p=engine.SHORE_CLUES[i];vm.runInContext(`state.x=${p.x-1};state.y=${p.y};save();draw()`,ui.context);ui.click('interact');assert.ok(ui.scene().innerHTML.includes(p.name));assert.deepEqual(ui.read().state.campaign.discoveries,Array.from({length:i+1},(_,n)=>n));ui.click('clueClose');}
 assert.match(ui.nodes.get('objective').textContent,/長老へ報告/);
 ui=boot(ui.read());assert.deepEqual(ui.read().state.campaign.discoveries,[0,1,2]);assert.ok(engine.validState(ui.read().state));
 vm.runInContext('state.x=31;state.y=8;draw()',ui.context);ui.click('interact');assert.deepEqual(ui.read().state.campaign.discoveries,[0,1,2]);
});
test('highland repair route enforces order and persists through production UI',()=>{
 const s=engine.makeState();s.badges=[0,1];s.region=2;s.campaign={schema:3,chapter:5,step:1,baseWins:9,baseCaptures:3,claimed:[1,2,3,4],discoveries:[],regionWins:0};let ui=boot({state:s,battle:null});
 const second=engine.HIGHLAND_REPAIRS[1];vm.runInContext(`state.x=${second.x-1};state.y=${second.y};draw()`,ui.context);ui.click('interact');assert.match(ui.nodes.get('toast').textContent,/工房の主炉/);assert.deepEqual(ui.read().state.campaign.discoveries,[]);
 for(let i=0;i<engine.HIGHLAND_REPAIRS.length;i++){const p=engine.HIGHLAND_REPAIRS[i];vm.runInContext(`state.x=${p.x-1};state.y=${p.y};save();draw()`,ui.context);ui.click('interact');assert.ok(ui.scene().innerHTML.includes(p.name));assert.deepEqual(ui.read().state.campaign.discoveries,Array.from({length:i+1},(_,n)=>n));ui.click('repairClose');}
 assert.match(ui.nodes.get('objective').textContent,/長老へ報告/);ui=boot(ui.read());assert.deepEqual(ui.read().state.campaign.discoveries,[0,1,2]);assert.equal(ui.read().state.campaign.schema,4);
});
test('starshadow mirrors enforce their order through the production interaction button',()=>{
 const s=engine.makeState();s.badges=[0,1,2];s.region=3;s.campaign={schema:4,chapter:7,step:1,baseWins:20,baseCaptures:8,claimed:[1,2,3,4,5,6],discoveries:[],regionWins:5};let ui=boot({state:s,battle:null});
 const second=engine.STARSHADOW_MIRRORS[1];vm.runInContext(`state.x=${second.x-1};state.y=${second.y};draw();interactMirror()`,ui.context);assert.match(ui.nodes.get('toast').textContent,/月影の鏡/);assert.deepEqual(ui.read().state.campaign.discoveries,[]);
 for(let i=0;i<engine.STARSHADOW_MIRRORS.length;i++){const p=engine.STARSHADOW_MIRRORS[i];vm.runInContext(`state.x=${p.x-1};state.y=${p.y};save();draw();interactMirror()`,ui.context);assert.ok(ui.scene().innerHTML.includes(p.name));assert.deepEqual(ui.read().state.campaign.discoveries,Array.from({length:i+1},(_,n)=>n));ui.click('mirrorClose');}
 assert.match(ui.nodes.get('objective').textContent,/長老へ報告/);ui=boot(ui.read());assert.deepEqual(ui.read().state.campaign.discoveries,[0,1,2]);assert.ok(engine.validState(ui.read().state));
});
