import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';import * as engine from '../dist/engine.js';
// DOM contract harness: executes production UI handlers without a browser runtime.
function boot(saved,backup){const nodes=new Map(),timers=[];const storage=new Map();if(saved!==undefined&&saved!==null)storage.set('lumina-save-v1',typeof saved==='string'?saved:JSON.stringify(saved));if(backup!==undefined&&backup!==null)storage.set('lumina-save-v1-backup',typeof backup==='string'?backup:JSON.stringify(backup));
class Element{constructor(tag='DIV',attrs={}){this.tagName=tag.toUpperCase();this.attrs=attrs;this.dataset={};this.children=[];this.listeners={};this.className='';this.classList={add:()=>{},remove:()=>{}};for(const [k,v]of Object.entries(attrs))if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=v;this.id=attrs.id;if(this.id)nodes.set(this.id,this);}set innerHTML(html){this.html=html;for(const c of this.children)if(c.id)nodes.delete(c.id);this.children=[];for(const match of html.matchAll(/<([a-zA-Z]+)\b([^>]*)>/g)){const attrs={};for(const a of match[2].matchAll(/([\w-]+)="([^"]*)"/g))attrs[a[1]]=a[2];if(/\bdisabled\b/.test(match[2]))attrs.disabled=true;const el=new Element(match[1],attrs);el.disabled=attrs.disabled;this.children.push(el);}}get innerHTML(){return this.html;}querySelectorAll(sel){const a=sel.match(/^\[([^\]]+)\]$/)?.[1];return this.children.filter(c=>a&&Object.hasOwn(c.attrs,a));}addEventListener(event,fn){this.listeners[event]=fn;}setPointerCapture(){}click(){if(!this.disabled)this.onclick?.({target:this,preventDefault(){}});}getContext(){return new Proxy({},{get:(_,k)=>()=>{}});}getBoundingClientRect(){return {width:390,height:390};}}
const doc=new Element();doc.innerHTML=fs.readFileSync('dist/index.html','utf8');doc.getElementById=id=>nodes.get(id);doc.hidden=false;doc.createElement=tag=>new Element(tag);doc.querySelectorAll=Element.prototype.querySelectorAll.bind(doc);const noop=()=>{};
class FakeAudio{constructor(src){this.src=src;}play(){return Promise.resolve();}pause(){}}
const context={...engine,document:doc,window:{addEventListener:noop},navigator:{},Image:class{constructor(){this.complete=false;}},Audio:FakeAudio,localStorage:{getItem:key=>storage.get(key)??null,setItem:(key,val)=>storage.set(key,val)},setTimeout:(fn)=>{timers.push(fn);return 1;},clearTimeout:noop,setInterval:()=>1,clearInterval:noop,console,Date,Math,JSON,Number,Object,Array,URL,Blob};vm.createContext(context);const code=fs.readFileSync('dist/game.js','utf8').replace(/^import[^\n]+\n/,'');vm.runInContext(code,context);return {nodes,scene:()=>nodes.get('scene'),read:()=>JSON.parse(storage.get('lumina-save-v1')),backup:()=>storage.get('lumina-save-v1-backup'),click:id=>{assert.ok(nodes.get(id),id+' exists');nodes.get(id).click();},data:(key)=>nodes.get('scene').querySelectorAll('['+key+']'),flush:()=>{while(timers.length)timers.shift()();},context};}
test('new game starter, menu, codex, bag and map render using actual UI handlers',()=>{const ui=boot();assert.equal(ui.data('data-starter').length,3);ui.data('data-starter')[0].click();assert.ok(engine.validState(ui.read().state));ui.click('menu');assert.ok(ui.scene().innerHTML.includes('セーブを書き出す'));ui.click('closeModal');ui.click('dexBtn');assert.equal(ui.data('data-dex').length,16);ui.click('closeModal');ui.click('partyBtn');assert.equal(ui.data('data-lead').length,1);ui.click('closeModal');ui.click('bagBtn');assert.ok(ui.scene().innerHTML.includes('捕獲クリスタル'));ui.click('closeModal');ui.click('mapBtn');assert.equal(ui.data('data-travel').length,4);assert.ok(ui.data('data-travel')[1].disabled);});
test('healer and shop transactions, persistence and reload',()=>{const s=engine.makeState();s.x=7;s.y=8;s.party[0].hp=1;let ui=boot({state:s,battle:null});ui.click('interact');assert.equal(ui.read().state.party[0].hp,engine.maxHP(s.party[0]));const saved=ui.read();saved.state.x=10;saved.state.y=8;ui=boot(saved);ui.click('interact');ui.click('buyBalls');assert.equal(ui.read().state.coins,50);assert.equal(ui.read().state.balls,17);assert.ok(engine.validState(ui.read().state));const ui2=boot(ui.read());assert.equal(ui2.read().state.balls,17);});
test('actual battle handlers resume save, attack, victory and ending return',()=>{const s=engine.makeState();s.party=[engine.createMonster(4,35),engine.createMonster(6,35)];s.badges=[0,1,2,3];const b=engine.encounter(s,3,true,true);let ui=boot({state:s,battle:b});let turns=0;while(!ui.read().battle.result&&turns++<40){ui.data('data-action').find(x=>x.dataset.action==='attack').click();ui.flush();}assert.equal(ui.read().battle.result,'win');assert.equal(ui.read().state.ended,true);ui.click('endBattle');assert.ok(ui.scene().innerHTML.includes('ルミナ島に光が戻った'));ui.click('postgame');assert.equal(ui.scene().className,'scene');assert.equal(ui.read().battle,null);});
test('party switch does not let a battle escape through closing a modal',()=>{const s=engine.makeState();s.party.push(engine.createMonster(2,5));const b=engine.encounter(s,0);const ui=boot({state:s,battle:b});ui.click('battleSwitch');ui.click('closeModal');assert.ok(ui.scene().innerHTML.includes('battle-actions'));ui.click('battleSwitch');ui.data('data-switch')[1].click();ui.flush();assert.equal(ui.read().battle.active,1);assert.equal(ui.read().battle.turn,1);});
test('corrupt current save restores backup and repairs current without overwriting backup',()=>{const s=engine.makeState(2);s.coins=777;const backup=JSON.stringify({state:s,battle:null});const ui=boot('{broken-json',backup);assert.equal(ui.read().state.coins,777);assert.equal(ui.read().state.party[0].id,2);assert.equal(ui.backup(),backup);});
