'use strict';
const {loot,combat,shop,enemies}=GameCore;
const $=id=>document.getElementById(id), slots=['weapon','armor','charm'],slotName={weapon:'剣',armor:'鎧',charm:'装飾'};
const specs={triple:{name:'三連斬',mult:3.2,cost:18,cooldown:9,cast:1.31,targets:1,hitFractions:[265/1310,500/1310,930/1310]},thrust:{name:'踏み込み突き',mult:1.35,cost:8,cooldown:3,cast:.715,targets:1,hitFractions:[325/715]},sweep:{name:'低い横薙ぎ',mult:1.7,cost:12,cooldown:5,cast:.735,targets:3,hitFractions:[315/735]},leap:{name:'跳び込み斬り',mult:2.4,cost:16,cooldown:7,cast:.82,targets:1,hitFractions:[430/820]},heal_potion:{name:'回復薬',type:'potion',hpBelow:.4,healRatio:.3,cast:.5,cooldown:15}};
const KEY='swordsman-integrated-v1';
function fresh(){const gear=slots.map((slot,id)=>({id,slot,baseLevel:1,quality:1,req:1,ops:[]}));return{version:1,level:1,xp:0,gold:200,materials:0,kills:0,wins:0,losses:0,seconds:0,cleared:0,nextId:3,rng:123456789,gear:gear.map(x=>x.id),bag:gear,enhance:{weapon:0,armor:0,charm:0},queue:Object.keys(specs),healAt:.4,zone:'balanced',autoBuy:false,state:{potions:20},log:[]};}
let s=fresh(),loadWarning='';try{const raw=localStorage.getItem(KEY);if(raw){const v=JSON.parse(raw);if(v.version!==1||!Array.isArray(v.bag)||!v.gear.every(id=>v.bag.some(x=>x.id===id))||!v.queue.every(id=>specs[id]))throw Error('保存形式');s=v;}}catch{loadWarning='保存データを読み込めませんでした。元の保存は上書きせず、新しい旅を表示しています。';}
let running=false,ready=false,goingTown=false,view=null,gen=null,next=null,p,foes=[],fightTime=0,totalBase=0,action=null,floating=[],lastTime=null,town=true,enemyLv=1,boss=false,combo,other,lastPaint=0;
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function random(){s.rng=(s.rng+0x6D2B79F5)>>>0;let x=s.rng;x=Math.imul(x^x>>>15,x|1);x^=x+Math.imul(x^x>>>7,x|61);return((x^x>>>14)>>>0)/4294967296;}
function player(){const q=loot.player(s.level,s.gear.map(id=>s.bag.find(x=>x.id===id)),s.enhance),skillBonus=q.skills.find(x=>x.id==='burst').mult/3.2;q.ordered=true;q.actions=s.queue.map(id=>({...specs[id],id,mult:specs[id].mult*skillBonus,hpBelow:s.healAt}));return q;}
function log(msg){s.log.unshift(msg);s.log=s.log.slice(0,80);}
function notice(msg){$('notice').textContent=msg;}
function persist(manual=false){if(loadWarning){if(manual)notice(loadWarning);return;}try{localStorage.setItem(KEY,JSON.stringify(s));if(manual)notice(gen?'直前の戦闘終了時点を保存しました。今の戦闘は終了時に保存します。':'保存しました。');}catch{notice('保存できませんでした。ブラウザの空き容量を確認してください。');}}
function beginBattle(){p=player();boss=s.level>=(s.cleared+1)*100;enemyLv=boss?(s.cleared+1)*100:Math.max(1,Math.min(Math.floor(s.level/10)*10,(s.cleared+1)*100-10));foes=enemies(enemyLv,boss,boss?1:1+Math.floor(random()*3));gen=combat.stream({player:p,enemies:foes,state:s.state,seed:Math.floor(random()*4294967296)});fightTime=0;totalBase=s.seconds;next=gen.next();action=null;floating=[];town=false;}
function accept(v){view=v;for(const e of v.events){if(e.type==='cast'){action=e;$('caption').textContent=specs[e.id]?.name||'通常攻撃';}else floating.push({...e,born:totalBase+e.time});}}
function finish(result){accept(result.view);s.state=result.state;s.seconds=totalBase+result.seconds;gen=null;next=null;
 if(result.win){s.wins++;s.kills+=foes.length;s.gold+=foes.length*(2+Math.floor(enemyLv/50))*(boss?5:1);let finds=0;
  for(let i=0;i<foes.length;i++){if(random()<.03)s.state.potions++;if(random()<.1){const it=loot.item(random,enemyLv,s.nextId++,false,p.magicFind,p.uniqueFind,s.zone);if(it.req<=s.level+100){s.bag.push(it);finds++;log('拾得：'+slotName[it.slot]+' 必要Lv.'+it.req+' '+(it.ops.map(o=>o.name).join(' / ')||'ノーマル・OPなし'));}}if(s.zone==='materials'&&random()<.15)s.materials++;}
  if(boss){s.cleared++;log('Lv.'+enemyLv+' の守護者を撃破 · '+result.seconds.toFixed(1)+'秒');}
  s.xp+=(boss?20:foes.length)*Math.min(1.2,enemyLv/s.level);const old=s.level;while(s.level<1000&&s.xp>=8+Math.floor(s.level/25)){s.xp-=8+Math.floor(s.level/25);s.level++;}if(s.level!==old)log('Lv.'+s.level+' に成長');
  notice('勝利 · '+result.seconds.toFixed(1)+'秒'+(finds?' · 装備 '+finds+'個を拾得':''));
 }else{s.losses++;log('Lv.'+enemyLv+' で'+(result.reason==='timeout'?'時間切れ':'敗北')+'。町で回復');s.state={potions:s.state.potions};goingTown=true;notice('町に帰還しました。装備・行動順・回復薬を見直せます。');}
 if(s.cleared>=10){running=false;goingTown=true;log('Lv.1000の守護者を撃破。旅を踏破！');notice('踏破おめでとう！ プレイ時間 '+(s.seconds/3600).toFixed(2)+'時間');}
 persist();if(goingTown){enterTown();}else if(running)beginBattle();renderUI();}
function enterTown(){town=true;running=false;goingTown=false;gen=null;next=null;action=null;p=player();view={hp:s.state.hp??p.hp,cp:s.state.cp??p.cp,potions:s.state.potions,foes:[],seconds:0,events:[]};if(s.autoBuy){const tx=shop.purchase({gold:s.gold,potions:s.state.potions});s.gold=tx.gold;s.state.potions=tx.potions;view.potions=tx.potions;if(tx.bought)log('町で回復薬を'+tx.bought+'個補充');}persist();renderUI();$('caption').textContent='町 · 次の冒険に備える';}
function renderQueue(){$('queue').innerHTML=s.queue.map((id,i)=>`<div class="action"><span>${i+1}</span><div><select aria-label="行動${i+1}" data-order="${i}">${Object.entries(specs).map(([k,v])=>`<option value="${k}" ${k===id?'selected':''}>${v.name}</option>`).join('')}</select><small>${id==='heal_potion'?'HP条件で使用 · 再使用15秒':`CP ${specs[id].cost} · ${specs[id].targets}体 · 再使用${specs[id].cooldown}秒`}</small></div><button data-up="${i}" aria-label="上へ" ${i===0?'disabled':''}>↑</button><button data-down="${i}" aria-label="下へ" ${i===4?'disabled':''}>↓</button></div>`).join('');}
function itemHTML(it,equipped=false){const locked=it.req>s.level;return `<article class="item"><div class="title"><strong>${slotName[it.slot]} ${it.unique?'★':''} 基礎Lv.${it.baseLevel}</strong><span class="${locked?'locked':'tag'}">必要Lv.${it.req}</span></div><div class="ops">${it.ops.length?it.ops.map(o=>esc(o.name)+'：'+esc(o.rolled||o.effect)).join('<br>'):'ノーマル · OPなし'}</div><span class="muted">品質 ${Math.round(it.quality*100)}%${equipped?' · 育成 +'+s.enhance[it.slot]:''}</span><div>${equipped?'<span class="tag">装備中</span>':`<button data-equip="${it.id}" ${!town||locked?'disabled':''}>装備</button><button data-salvage="${it.id}" ${!town?'disabled':''}>素材にする +1</button>`}</div></article>`;}
function renderUI(){p=gen?p:player();$('level').textContent='Lv.'+s.level;$('xp').value=s.level>=1000?1:s.xp/(8+Math.floor(s.level/25));$('xpText').textContent=s.level>=1000?'最大レベル':s.xp.toFixed(1)+' / '+(8+Math.floor(s.level/25));$('start').textContent=s.cleared>=10?'旅を踏破':running?'一時停止':gen?'戦闘を再開':'冒険を始める';$('start').disabled=!ready||s.cleared>=10;$('town').textContent=goingTown?'戦闘後に帰還':town?'町に滞在中':'町へ';$('town').disabled=town;$('healAt').value=String(s.healAt);$('zone').value=s.zone;$('autoBuy').checked=s.autoBuy;
 $('money').textContent=s.gold+' G · 素材 '+s.materials;$('potionCount').textContent='回復薬 '+(view?.potions??s.state.potions)+'個';$('place').textContent=town?'旅支度の町':(boss?'守護者':'狩場')+' Lv.'+enemyLv+' · '+foes.length+'体';
 const q=player();$('stats').innerHTML=[['攻撃',q.atk.toFixed(1)],['防御',q.def.toFixed(1)],['攻撃速度',q.attackSpeed.toFixed(2)+'倍'],...Object.entries(q.stats)].map(([k,v])=>`<span>${k} ${v}</span>`).join('');$('gear').innerHTML=s.gear.map(id=>itemHTML(s.bag.find(x=>x.id===id),true)).join('');const bag=s.bag.filter(x=>!s.gear.includes(x.id));$('bagCount').textContent=bag.length+'個';$('bag').innerHTML=bag.slice().reverse().map(x=>itemHTML(x)).join('')||'<p class="muted">敵からの拾得品がここに並びます。</p>';
 $('buy').disabled=!town;$('shopState').textContent=town?'町に滞在中。回復薬を購入できます。':'「町へ」を押すと、今の戦闘が終わった後に入店できます。';$('enhance').innerHTML=slots.map(slot=>{const n=s.enhance[slot],cost=20*(n+1);return `<div><span>${slotName[slot]} +${n}</span><button data-enhance="${slot}" ${!town||n>=10||s.materials<cost?'disabled':''}>${n>=10?'最大育成':'育成 · 素材'+cost}</button></div>`;}).join('');$('summary').textContent=`討伐 ${s.kills}体 / 勝利 ${s.wins} / 敗北 ${s.losses} / 守護者 ${s.cleared}/10`;$('log').innerHTML=s.log.map(x=>'<li>'+esc(x)+'</li>').join('');renderVitals();}
function renderVitals(){const hp=view?.hp??p.hp,cp=view?.cp??p.cp;$('hp').value=hp/p.hp;$('cp').value=cp/p.cp;$('hpText').textContent=Math.ceil(hp)+' / '+Math.round(p.hp);$('cpText').textContent=Math.floor(cp)+' / '+Math.round(p.cp);$('potionCount').textContent='回復薬 '+(view?.potions??s.state.potions)+'個';const sec=Math.floor(gen?totalBase+fightTime:s.seconds);$('clock').textContent=Math.floor(sec/3600)+':'+String(Math.floor(sec/60)%60).padStart(2,'0')+':'+String(sec%60).padStart(2,'0');}
$('start').onclick=()=>{if(!ready)return;running=!running;if(running&&!gen)beginBattle();notice(running?'自動戦闘中。町では装備変更と買い物ができます。':'一時停止中。「戦闘を再開」で続けられます。');renderUI();};$('town').onclick=()=>{goingTown=true;running=true;notice('この戦闘が終わったら町に入ります。');renderUI();};$('save').onclick=()=>persist(true);
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.panel').forEach(el=>el.hidden=el.id!==b.dataset.tab);document.querySelectorAll('[data-tab]').forEach(el=>el.classList.toggle('selected',el===b));});
$('queue').onchange=e=>{if(e.target.dataset.order===undefined)return;const i=+e.target.dataset.order,j=s.queue.indexOf(e.target.value);[s.queue[i],s.queue[j]]=[s.queue[j],s.queue[i]];renderQueue();persist();notice('行動順を更新しました。次の戦闘から反映します。');};
$('queue').onclick=e=>{const b=e.target.closest('button');if(!b)return;const i=+(b.dataset.up??b.dataset.down),j=i+(b.dataset.up!==undefined?-1:1);if(j<0||j>4)return;[s.queue[i],s.queue[j]]=[s.queue[j],s.queue[i]];renderQueue();persist();};
$('healAt').onchange=e=>{s.healAt=+e.target.value;persist();};$('zone').onchange=e=>{s.zone=e.target.value;persist();};$('autoBuy').onchange=e=>{s.autoBuy=e.target.checked;persist();};
$('buy').onclick=()=>{if(!town)return;const tx=shop.purchase({gold:s.gold,potions:s.state.potions},{reserve:0},true);s.gold=tx.gold;s.state.potions=tx.potions;view.potions=tx.potions;notice(tx.bought?'回復薬を'+tx.bought+'個購入しました。':'所持金が足りないか、30個以上持っています。');persist();renderUI();};
$('equipment').onclick=e=>{const b=e.target.closest('button');if(!b||!town)return;if(b.dataset.equip!==undefined){const it=s.bag.find(x=>x.id===+b.dataset.equip);if(!it||it.req>s.level)return;s.gear[slots.indexOf(it.slot)]=it.id;p=player();s.state.hp=Math.min(s.state.hp??p.hp,p.hp);s.state.cp=Math.min(s.state.cp??p.cp,p.cp);view.hp=s.state.hp;view.cp=s.state.cp;log(slotName[it.slot]+'を変更');}else if(b.dataset.salvage!==undefined){const id=+b.dataset.salvage;if(s.gear.includes(id))return;s.bag=s.bag.filter(x=>x.id!==id);s.materials++;}persist();renderUI();};
$('enhance').onclick=e=>{const slot=e.target.dataset.enhance;if(!slot||!town)return;const cost=20*(s.enhance[slot]+1);if(s.materials<cost||s.enhance[slot]>=10)return;s.materials-=cost;s.enhance[slot]++;log(slotName[slot]+' 育成 +'+s.enhance[slot]);persist();renderUI();};
document.addEventListener('visibilitychange',()=>{if(document.hidden){running=false;persist();renderUI();}lastTime=null;});
const canvas=$('battle'),g=canvas.getContext('2d'),colors={physical:'#8cb9ae',fire:'#e6a069',water:'#88c9e4',wind:'#b8cf93',earth:'#c6a16a',light:'#eee0a6',dark:'#bb9ad8'},elName={physical:'無',fire:'火',water:'水',wind:'風',earth:'土',light:'光',dark:'闇'};
function enemy(e,i,now){if(e.hp<=0)return;const x=610+i*88,y=369-i*15,bob=Math.sin(now*2+i)*3,scale=boss?1.3:1;g.save();g.translate(x,y);g.scale(scale,scale);g.fillStyle='#07131c80';g.beginPath();g.ellipse(0,9,44,10,0,0,Math.PI*2);g.fill();g.translate(0,bob);const glow=g.createRadialGradient(-12,-49,2,0,-25,62);glow.addColorStop(0,colors[e.element]);glow.addColorStop(1,'#244653');g.fillStyle=glow;g.beginPath();g.moveTo(-42,0);g.bezierCurveTo(-51,-20,-30,-31,-29,-57);g.bezierCurveTo(-24,-85,-6,-83,0,-98);g.bezierCurveTo(8,-75,28,-63,30,-44);g.bezierCurveTo(36,-26,52,-14,43,0);g.quadraticCurveTo(0,16,-42,0);g.fill();g.fillStyle='#102435';g.beginPath();g.ellipse(-12,-37,5,8,.2,0,7);g.ellipse(13,-37,5,8,-.2,0,7);g.fill();g.fillStyle='#f4f0c6';g.fillRect(-14,-41,3,4);g.fillRect(11,-41,3,4);g.restore();g.fillStyle='#0a1720';g.fillRect(x-35,y-128,70,5);g.fillStyle=colors[e.element];g.fillRect(x-35,y-128,70*e.hp/e.maxHp,5);g.font='12px sans-serif';g.textAlign='center';g.fillStyle='#d6dedb';g.fillText((boss?'守護霊':'精霊')+' · '+elName[e.element],x,y-139);}
function draw(now){g.clearRect(0,0,900,460);const bg=g.createLinearGradient(0,0,0,460);bg.addColorStop(0,'#10202e');bg.addColorStop(1,'#34474a');g.fillStyle=bg;g.fillRect(0,0,900,460);g.fillStyle='#c3d1bc';g.globalAlpha=.16;g.beginPath();g.arc(710,90,39,0,7);g.fill();g.globalAlpha=1;for(let i=0;i<12;i++){g.fillStyle=i%2?'#172e38':'#203742';g.fillRect(i*87+15,110+(i*41)%100,13,255);g.beginPath();g.ellipse(i*87+18,120+(i*41)%100,75,80,0,0,7);g.fill();}g.fillStyle='#29413e';g.fillRect(0,373,900,87);g.strokeStyle='#567064';g.lineWidth=1;for(let i=0;i<28;i++){const x=i*37%900,y=390+i*13%65;g.beginPath();g.moveTo(x,y);g.lineTo(x+9,y-3);g.stroke();}if(!ready)return;
 const a=action,elapsed=a?(fightTime-a.time)/a.duration:1;g.save();const advance=a&&a.id!=='heal_potion'&&elapsed>=0&&elapsed<1?140*Math.min(1,elapsed/.18,(1-elapsed)/.18):0;g.translate(5+advance,14);g.fillStyle='#07151c80';g.beginPath();g.ellipse(290,346,63,13,0,0,7);g.fill();if(a&&elapsed<1&&elapsed>=0){if(a.id==='triple')combo(elapsed*1310);else if(a.id==='heal_potion'){other(0,0,true);g.strokeStyle='#a5f0bc';g.shadowColor='#76eda8';g.shadowBlur=15;g.lineWidth=3;for(let i=0;i<5;i++){const x=230+i*26,y=300-(elapsed*130+i*21)%130;g.beginPath();g.moveTo(x-4,y);g.lineTo(x+4,y);g.moveTo(x,y-4);g.lineTo(x,y+4);g.stroke();}}else{const k=a.id==='sweep'?1:a.id==='leap'?2:0;other(k,elapsed*[715,735,820][k]);}}else other(0,0,true);g.restore();(view?.foes||[]).forEach((e,i)=>enemy(e,i,now));
 const stamp=gen?totalBase+fightTime:s.seconds;floating=floating.filter(e=>stamp-e.born<.65);for(const e of floating){const age=stamp-e.born;if(age<0)continue;const x=e.type==='hurt'?270:610+e.target*88,y=e.type==='hurt'?180:230-e.target*15;g.globalAlpha=Math.max(0,1-age/.65);g.fillStyle=e.type==='hurt'?'#f1b1a0':e.crit?'#ffe6a1':'#f8f3d9';g.font=(e.crit?'bold 25':'bold 20')+'px sans-serif';g.textAlign='center';g.fillText(e.type==='miss'?'MISS':Math.round(e.damage),x,y-age*50);if(e.type==='hit'&&age<.2){g.strokeStyle='#fff2be';g.shadowColor='#efbd68';g.shadowBlur=15;g.lineWidth=2;for(let i=0;i<6;i++){const ang=i*Math.PI/3;g.beginPath();g.moveTo(x+Math.cos(ang)*8,315+Math.sin(ang)*8);g.lineTo(x+Math.cos(ang)*(15+age*110),315+Math.sin(ang)*(15+age*110));g.stroke();}g.shadowBlur=0;}g.globalAlpha=1;}}
function tick(now){try{const dt=lastTime===null?0:Math.min(.1,(now-lastTime)/1000);lastTime=now;if(running&&gen){fightTime+=dt;let guard=0;while(next&&guard++<100){const v=next.done?next.value.view:next.value;if(v.seconds>fightTime+1e-8)break;if(next.done){finish(next.value);break;}accept(v);next=gen.next();}}draw(now/1000);if(now-lastPaint>100){renderVitals();lastPaint=now;}}catch(e){running=false;notice('戦闘を停止しました：'+e.message);console.error(e);}requestAnimationFrame(tick);}
renderQueue();p=player();renderUI();Promise.all([SwordArt.load('../restored/connected-combo.webp'),SwordArt.load('../restored/skill-motion-set.webp')]).then(([a,b])=>{combo=SwordArt.combo(g,a);other=SwordArt.other(g,b);ready=true;enterTown();notice(loadWarning||'「冒険を始める」で戦闘開始。行動順を並べ、拾った装備は町で装備できます。');}).catch(e=>{notice('素材を読み込めませんでした。ページを再読み込みしてください。');console.error(e);});requestAnimationFrame(tick);
