'use strict';
const {loot,combat,shop,enemies}=GameCore;
const $=id=>document.getElementById(id), slots=['weapon','armor','charm'],slotName={weapon:'剣',armor:'鎧',charm:'装飾'};
const specs={triple:{name:'三連斬',mult:3.2,cost:18,cooldown:9,cast:1.31,targets:1,hitFractions:[265/1310,500/1310,930/1310]},thrust:{name:'踏み込み突き',mult:1.35,cost:8,cooldown:3,cast:.715,targets:1,hitFractions:[325/715]},sweep:{name:'低い横薙ぎ',mult:1.7,cost:12,cooldown:5,cast:.735,targets:3,hitFractions:[315/735]},leap:{name:'跳び込み斬り',mult:2.4,cost:16,cooldown:7,cast:.82,targets:1,hitFractions:[430/820]},heal_potion:{name:'回復薬',type:'potion',hpBelow:.4,healRatio:.3,cast:.5,cooldown:15}};
Object.assign(specs,{
 flame:{name:'焔の飛び込み',element:'fire',powerSource:'weapon',motion:2,mult:3,cost:20,cooldown:8,cast:.82,targets:1,hitFractions:[430/820]},
 frost:{name:'氷牙薙ぎ',element:'water',powerSource:'weapon',motion:1,mult:1.45,cost:18,cooldown:7,cast:.735,targets:3,hitFractions:[315/735],procs:[{type:'cold',chance:1,duration:2}]},
 thunder:{name:'雷光突き',element:'wind',powerSource:'weapon',motion:0,mult:2,cost:14,cooldown:5,cast:.715,targets:1,hitFractions:[325/715],procs:[{type:'stun',chance:.25,duration:1}]}
});
// Keep active poses; shorten only opening/return holds for connected combat.
const motionProfiles={
 basic:{source:[200,65,85,85],flow:[80,85,160,80],hits:[2]},
 triple:{source:[200,65,85,85,65,65,85,90,130,60,160,220],flow:[80,65,85,85,65,65,85,90,130,60,160,80],hits:[2,5,10]},
 thrust:{source:[260,65,150,240],flow:[80,65,150,80],hits:[2]},
 sweep:{source:[230,85,160,260],flow:[80,85,160,80],hits:[2]},
 leap:{source:[210,220,100,290],flow:[80,220,100,80],hits:[2]}
};
function motionProfile(id){return motionProfiles[id==='flame'?'leap':id==='frost'?'sweep':id==='thunder'?'thrust':id];}
function poseTime(id,elapsed){const m=motionProfile(id);if(!m)return 0;let t=Math.max(0,Math.min(1,elapsed))*m.flow.reduce((a,b)=>a+b,0),offset=0;for(let i=0;i<m.flow.length;i++){if(t<=m.flow[i]){if(i===m.flow.length-1)return offset-.001;if(i===0&&id!=='triple'&&id!=='basic')return m.source[0]+Math.min(m.source[1]-.001,t/m.flow[i]*m.source[1]);return offset+t/m.flow[i]*m.source[i];}t-=m.flow[i];offset+=m.source[i];}return offset-0.001;}
for(const [id,spec] of Object.entries(specs)){const m=motionProfile(id);if(!m)continue;const duration=m.flow.reduce((a,b)=>a+b,0);spec.cast=duration/1000;spec.hitFractions=m.hits.map(i=>m.flow.slice(0,i).reduce((a,b)=>a+b,0)/duration);}
const KEY='swordsman-integrated-v1';
function fresh(){const gear=slots.map((slot,id)=>({id,slot,baseLevel:1,quality:1,req:1,ops:[]}));return{version:1,level:1,xp:0,gold:200,materials:0,kills:0,wins:0,losses:0,seconds:0,cleared:0,nextId:3,rng:123456789,gear:gear.map(x=>x.id),bag:gear,enhance:{weapon:0,armor:0,charm:0},queue:['triple','thrust','sweep','leap','heal_potion'],healAt:.4,zone:'balanced',autoBuy:false,state:{potions:20},log:[]};}
let s=fresh(),loadWarning='';try{const raw=localStorage.getItem(KEY);if(raw){const v=JSON.parse(raw);if(v.version!==1||!Array.isArray(v.bag)||!v.gear.every(id=>v.bag.some(x=>x.id===id))||!v.queue.every(id=>specs[id]))throw Error('保存形式');s=v;}}catch{loadWarning='保存データを読み込めませんでした。元の保存は上書きせず、新しい旅を表示しています。';}
const statNames=['力','敏捷','健康','知恵','知識','威厳','運'];
if(!s.allocation){const n=s.level-1;s.allocation={力:Math.floor(n*1.5),敏捷:Math.floor(n*.5),健康:n,知恵:0,知識:0,威厳:0,運:4*n-Math.floor(n*1.5)-Math.floor(n*.5)-n};}
function unspent(){return Math.max(0,4*(s.level-1)-Object.values(s.allocation).reduce((a,b)=>a+b,0));}
let normalAttackOnly=false,heroMotion=null,forestImage=null,monsterImage=null,supportDraw=null,hurtStamp=-99,townPose="idle";
const skillIcons={triple:"⚔",thrust:"➶",sweep:"◒",leap:"➹",heal_potion:"✚",flame:"♨",frost:"❄",thunder:"ϟ"};
const skillNames={triple:"三連斬",thrust:"突き",sweep:"横薙ぎ",leap:"飛び込み",heal_potion:"回復薬",flame:"焔の刃",frost:"氷牙",thunder:"雷光"};
let liveCooldowns={};
let running=false,ready=false,goingTown=false,view=null,gen=null,next=null,p,foes=[],fightTime=0,totalBase=0,action=null,heroAdvance=0,elementBursts=[],floating=[],lastTime=null,town=true,enemyLv=1,boss=false,combo,other,lastPaint=0;
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function random(){s.rng=(s.rng+0x6D2B79F5)>>>0;let x=s.rng;x=Math.imul(x^x>>>15,x|1);x^=x+Math.imul(x^x>>>7,x|61);return((x^x>>>14)>>>0)/4294967296;}
function player(){const q=loot.player(s.level,s.gear.map(id=>s.bag.find(x=>x.id===id)),s.enhance,s.allocation),skillBonus=q.skills.find(x=>x.id==='burst').mult/3.2;q.ordered=true;q.actions=normalAttackOnly?[]:s.queue.map(id=>({...specs[id],id,mult:specs[id].mult*skillBonus,hpBelow:s.healAt}));return q;}
function log(msg){s.log.unshift(msg);s.log=s.log.slice(0,80);}
function notice(msg){$('notice').textContent=msg;}
function persist(manual=false){if(loadWarning){if(manual)notice(loadWarning);return;}try{localStorage.setItem(KEY,JSON.stringify(s));if(manual)notice(gen?'直前の戦闘終了時点を保存しました。今の戦闘は終了時に保存します。':'保存しました。');}catch{notice('保存できませんでした。ブラウザの空き容量を確認してください。');}}
function beginBattle(){townPose="idle";p=player();boss=s.level>=(s.cleared+1)*100;enemyLv=boss?(s.cleared+1)*100:Math.max(1,Math.min(Math.floor(s.level/10)*10,(s.cleared+1)*100-10));foes=enemies(enemyLv,boss,boss?1:1+Math.floor(random()*3));gen=combat.stream({player:p,enemies:foes,state:s.state,seed:Math.floor(random()*4294967296)});fightTime=0;totalBase=s.seconds;next=gen.next();floating=[];town=false;}
function accept(v){view=v;for(const e of v.events){if(e.type==='cast'){action={...e,born:totalBase+e.time};liveCooldowns[e.id]=totalBase+e.time+(specs[e.id]?.cooldown||0); $('caption').textContent=specs[e.id]?.name||'通常攻撃 · 斜め振り下ろし';}else{if(e.type==='hurt'){hurtStamp=totalBase+e.time;heroMotion?.hurt(hurtStamp);}floating.push({...e,born:totalBase+e.time});if(e.type==='hit'&&specs[e.id]?.element)elementBursts.push({...e,born:totalBase+e.time});}}}
function finish(result){accept(result.view);s.state=result.state;s.seconds=totalBase+result.seconds;gen=null;next=null;
 if(result.win){townPose="victory";s.wins++;s.kills+=foes.length;s.gold+=foes.length*(2+Math.floor(enemyLv/50))*(boss?5:1);let finds=0;
  for(let i=0;i<foes.length;i++){if(random()<.03)s.state.potions++;if(random()<.1){const it=loot.item(random,enemyLv,s.nextId++,false,p.magicFind,p.uniqueFind,s.zone);if(it.req<=s.level+100){s.bag.push(it);finds++;log('拾得：'+slotName[it.slot]+' 必要Lv.'+it.req+' '+(it.ops.map(o=>o.name).join(' / ')||'ノーマル・OPなし'));}}if(s.zone==='materials'&&random()<.15)s.materials++;}
  if(boss){s.cleared++;log('Lv.'+enemyLv+' の守護者を撃破 · '+result.seconds.toFixed(1)+'秒');}
  s.xp+=(boss?20:foes.length)*Math.min(1.2,enemyLv/s.level);const old=s.level;while(s.level<1000&&s.xp>=8+Math.floor(s.level/25)){s.xp-=8+Math.floor(s.level/25);s.level++;}if(s.level!==old)log('Lv.'+s.level+' に成長');
  notice('勝利 · '+result.seconds.toFixed(1)+'秒'+(finds?' · 装備 '+finds+'個を拾得':''));
 }else{townPose="defeat";s.losses++;log('Lv.'+enemyLv+' で'+(result.reason==='timeout'?'時間切れ':'敗北')+'。町で回復');s.state={potions:s.state.potions};goingTown=true;notice('町に帰還しました。装備・行動順・回復薬を見直せます。');}
 if(s.cleared>=10){running=false;goingTown=true;log('Lv.1000の守護者を撃破。旅を踏破！');notice('踏破おめでとう！ プレイ時間 '+(s.seconds/3600).toFixed(2)+'時間');}
 persist();if(goingTown){enterTown();}else if(running)beginBattle();renderUI();}
function enterTown(){town=true;running=false;goingTown=false;gen=null;next=null;action=null;heroAdvance=0;heroMotion?.reset();p=player();view={hp:s.state.hp??p.hp,cp:s.state.cp??p.cp,potions:s.state.potions,foes:[],seconds:0,events:[]};if(s.autoBuy){const tx=shop.purchase({gold:s.gold,potions:s.state.potions});s.gold=tx.gold;s.state.potions=tx.potions;view.potions=tx.potions;if(tx.bought)log('町で回復薬を'+tx.bought+'個補充');}persist();renderUI();$('caption').textContent='町 · 次の冒険に備える';}
function renderQueue(){$('queue').innerHTML=s.queue.map((id,i)=>`<div class="action"><span>${i+1}</span><div><select aria-label="行動${i+1}" data-order="${i}">${Object.entries(specs).map(([k,v])=>`<option value="${k}" ${k===id?'selected':''}>${v.name}</option>`).join('')}</select><small>${id==='heal_potion'?'HP条件で使用 · 再使用15秒':`CP ${specs[id].cost} · ${specs[id].targets}体 · ${specs[id].element?({fire:'火',water:'水',wind:'風（雷）'}[specs[id].element])+'属性 · ':''}再使用${specs[id].cooldown}秒`}</small></div><button data-up="${i}" aria-label="上へ" ${i===0?'disabled':''}>↑</button><button data-down="${i}" aria-label="下へ" ${i===4?'disabled':''}>↓</button></div>`).join('');}
function comparisonHTML(it){const c=GearCompare.compare(loot,s.level,s.gear.map(id=>s.bag.find(x=>x.id===id)),s.enhance,it,s.allocation);const row=r=>`<tr><th scope="row">${r.label}</th><td>${r.before.toFixed(r.digits)}${r.unit}</td><td>${r.after.toFixed(r.digits)}${r.unit}</td><td class="${r.delta>0?'gain':r.delta<0?'loss':'muted'}">${r.delta>0?'+':''}${r.delta.toFixed(r.digits)}${r.unit==='%'?'pt':r.unit}</td></tr>`;return `<div class="comparison"><p class="compare-heading">${c.locked?'装備不可 · あと'+(it.req-s.level)+'Lv／現在Lvでの仮比較':'今の'+slotName[it.slot]+'から替えた場合'}</p><table aria-label="装備変更の能力比較"><thead><tr><th>能力</th><th>現在</th><th>変更後</th><th>差</th></tr></thead><tbody>${c.rows.slice(0,4).map(row).join('')}</tbody></table><details><summary>その他の能力差・今の装備のOP</summary>${c.rows.length>4?`<table><tbody>${c.rows.slice(4).map(row).join('')}</tbody></table>`:'<p class="muted">その他の表示対象能力に差はありません。</p>'}<p class="muted">外れる装備：基礎Lv.${c.current.baseLevel}／品質${Math.round(c.current.quality*100)}%</p><div class="ops">${c.current.ops.length?c.current.ops.map(o=>esc(o.name)+'：'+esc(o.rolled||o.effect)).join('<br>'):'現在の装備はOPなし'}</div><p class="muted">状態異常・追加属性ダメージなどは双方のOPを確認してください。育成＋${s.enhance[it.slot]}を引き継いだ比較です。</p></details></div>`;}
function itemHTML(it,equipped=false){const locked=it.req>s.level;return `<article class="item"><div class="title"><strong>${slotName[it.slot]} ${it.unique?'★':''} 基礎Lv.${it.baseLevel}</strong><span class="${locked?'locked':'tag'}">必要Lv.${it.req}</span></div><div class="ops">${it.ops.length?it.ops.map(o=>esc(o.name)+'：'+esc(o.rolled||o.effect)).join('<br>'):'ノーマル · OPなし'}</div><span class="muted">品質 ${Math.round(it.quality*100)}%${equipped?' · 育成 +'+s.enhance[it.slot]:''}</span>${equipped?'':comparisonHTML(it)}<div>${equipped?'<span class="tag">装備中</span>':`<button data-equip="${it.id}" ${!town||locked?'disabled':''}>${locked?'Lv不足':!town?'町で装備':'この装備に替える'}</button><button data-salvage="${it.id}" ${!town?'disabled':''}>素材にする +1</button>`}</div></article>`;}
function renderUI(){$('normalOnly').disabled=!town;$('normalOnly').textContent=normalAttackOnly?'通常攻撃のみ：ON（押すと行動順へ戻る）':'通常攻撃だけで試す';p=gen?p:player();$('level').textContent='Lv.'+s.level;$('xp').value=s.level>=1000?1:s.xp/(8+Math.floor(s.level/25));$('xpText').textContent=s.level>=1000?'最大レベル':s.xp.toFixed(1)+' / '+(8+Math.floor(s.level/25));$('start').textContent=s.cleared>=10?'旅を踏破':running?'一時停止':gen?'戦闘を再開':'冒険を始める';$('start').disabled=!ready||s.cleared>=10;$('town').textContent=goingTown?'戦闘後に帰還':town?'町に滞在中':'町へ';$('town').disabled=town;$('healAt').value=String(s.healAt);$('zone').value=s.zone;$('autoBuy').checked=s.autoBuy;
 $('money').textContent=s.gold+' G · 素材 '+s.materials;$('potionCount').textContent='回復薬 '+(view?.potions??s.state.potions)+'個';$('place').textContent=town?'旅支度の町':(boss?'守護者':'狩場')+' Lv.'+enemyLv+' · '+foes.length+'体';
 const latest=s.bag.filter(x=>x.id>=3).at(-1);$('latestDrop').innerHTML=latest?`<strong>${slotName[latest.slot]} · 必要Lv.${latest.req}</strong><br><span class=muted>${latest.ops.map(o=>esc(o.name)).join(' / ')||'ノーマル・OPなし'}</span> <button id=compareLatest>装備と比較</button>`:'旅で見つけた装備がここに届きます。';if(latest)$('compareLatest').onclick=()=>document.querySelector('[data-tab=equipment]').click();const q=player();$('allocation').innerHTML='<p>未使用 '+unspent()+' ポイント · 1レベルにつき4ポイント</p>'+statNames.map(k=>`<div class=setting><span>${k} ${q.stats[k]}（配分 ${s.allocation[k]||0}）</span><button data-stat="${k}" ${!town||!unspent()?'disabled':''}>＋1</button></div>`).join('');$('stats').innerHTML=[['攻撃',q.atk.toFixed(1)],['防御',q.def.toFixed(1)],['攻撃速度',q.attackSpeed.toFixed(2)+'倍'],...Object.entries(q.stats)].map(([k,v])=>`<span>${k} ${v}</span>`).join('');$('gear').innerHTML=s.gear.map(id=>itemHTML(s.bag.find(x=>x.id===id),true)).join('');const bag=s.bag.filter(x=>!s.gear.includes(x.id));$('bagCount').textContent=bag.length+'個';$('bag').innerHTML=bag.slice().reverse().map(x=>itemHTML(x)).join('')||'<p class="muted">敵からの拾得品がここに並びます。</p>';
 $('buy').disabled=!town;$('shopState').textContent=town?'町に滞在中。回復薬を購入できます。':'「町へ」を押すと、今の戦闘が終わった後に入店できます。';$('enhance').innerHTML=slots.map(slot=>{const n=s.enhance[slot],cost=20*(n+1);return `<div><span>${slotName[slot]} +${n}</span><button data-enhance="${slot}" ${!town||n>=10||s.materials<cost?'disabled':''}>${n>=10?'最大育成':'育成 · 素材'+cost}</button></div>`;}).join('');$('summary').textContent=`討伐 ${s.kills}体 / 勝利 ${s.wins} / 敗北 ${s.losses} / 守護者 ${s.cleared}/10`;$('log').innerHTML=s.log.map(x=>'<li>'+esc(x)+'</li>').join('');renderVitals();}
function renderActionStrip(){const stamp=gen?totalBase+fightTime:s.seconds;const queue=normalAttackOnly?['basic']:s.queue;$('actionStrip').innerHTML=queue.map((id,i)=>{const cd=Math.max(0,(liveCooldowns[id]||0)-stamp);return `<div class="action-card ${running&&action?.id===id?'active':''}"><span class="order">${i+1}</span><span class="skill-icon skill-${id}" aria-hidden="true">${skillIcons[id]||'⚔'}</span><span class="skill-name">${skillNames[id]||'斜め斬り'}</span><small class="cooldown">${id==='heal_potion'?'HP '+Math.round(s.healAt*100)+'%':cd>0?'あと '+cd.toFixed(1)+'秒':'準備OK'}</small></div>`;}).join('');$('activeSkill').textContent=town?'町':running?'自動戦闘中':'一時停止';}
function renderVitals(){renderActionStrip();const hp=view?.hp??p.hp,cp=view?.cp??p.cp;$('hp').value=hp/p.hp;$('cp').value=cp/p.cp;$('hpText').textContent=Math.ceil(hp)+' / '+Math.round(p.hp);$('cpText').textContent=Math.floor(cp)+' / '+Math.round(p.cp);$('potionCount').textContent='回復薬 '+(view?.potions??s.state.potions)+'個';const sec=Math.floor(gen?totalBase+fightTime:s.seconds);$('clock').textContent=Math.floor(sec/3600)+':'+String(Math.floor(sec/60)%60).padStart(2,'0')+':'+String(sec%60).padStart(2,'0');}
$('allocation').onclick=e=>{const k=e.target.dataset.stat;if(!town||!statNames.includes(k)||unspent()<1)return;s.allocation[k]=(s.allocation[k]||0)+1;persist();renderUI();};
$('normalOnly').onclick=()=>{if(!town)return;normalAttackOnly=!normalAttackOnly;renderUI();notice(normalAttackOnly?'通常攻撃だけで戦います。「冒険を始める」で確認できます。':'設定した行動順で戦います。');};
$('elementPreset').onclick=()=>{s.queue=['flame','frost','thunder','heal_potion','thrust'];s.state.cursor=0;renderQueue();persist();notice('炎→氷→雷→回復薬→突きに設定。'+(gen?'次の戦闘から反映します。':'「冒険を始める」で試せます。'));};
$('start').onclick=()=>{if(!ready)return;running=!running;if(running&&!gen)beginBattle();notice(running?'自動戦闘中。町では装備変更と買い物ができます。':'一時停止中。「戦闘を再開」で続けられます。');renderUI();};$('town').onclick=()=>{goingTown=true;running=true;notice('この戦闘が終わったら町に入ります。');renderUI();};$('save').onclick=()=>persist(true);
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.panel').forEach(el=>el.hidden=el.id!==b.dataset.tab);document.querySelectorAll('[data-tab]').forEach(el=>el.classList.toggle('selected',el===b));});
$('queue').onchange=e=>{if(e.target.dataset.order===undefined)return;const i=+e.target.dataset.order,j=s.queue.indexOf(e.target.value);if(j<0)s.queue[i]=e.target.value;else [s.queue[i],s.queue[j]]=[s.queue[j],s.queue[i]];renderQueue();persist();notice('行動順を更新しました。次の戦闘から反映します。');};
$('queue').onclick=e=>{const b=e.target.closest('button');if(!b)return;const i=+(b.dataset.up??b.dataset.down),j=i+(b.dataset.up!==undefined?-1:1);if(j<0||j>4)return;[s.queue[i],s.queue[j]]=[s.queue[j],s.queue[i]];renderQueue();persist();};
$('healAt').onchange=e=>{s.healAt=+e.target.value;persist();};$('zone').onchange=e=>{s.zone=e.target.value;persist();};$('autoBuy').onchange=e=>{s.autoBuy=e.target.checked;persist();};
$('buy').onclick=()=>{if(!town)return;const tx=shop.purchase({gold:s.gold,potions:s.state.potions},{reserve:0},true);s.gold=tx.gold;s.state.potions=tx.potions;view.potions=tx.potions;notice(tx.bought?'回復薬を'+tx.bought+'個購入しました。':'所持金が足りないか、30個以上持っています。');persist();renderUI();};
$('equipment').onclick=e=>{const b=e.target.closest('button');if(!b||!town)return;if(b.dataset.equip!==undefined){const it=s.bag.find(x=>x.id===+b.dataset.equip);if(!it||it.req>s.level)return;s.gear[slots.indexOf(it.slot)]=it.id;p=player();s.state.hp=Math.min(s.state.hp??p.hp,p.hp);s.state.cp=Math.min(s.state.cp??p.cp,p.cp);view.hp=s.state.hp;view.cp=s.state.cp;log(slotName[it.slot]+'を変更');}else if(b.dataset.salvage!==undefined){const id=+b.dataset.salvage;if(s.gear.includes(id))return;s.bag=s.bag.filter(x=>x.id!==id);s.materials++;}persist();renderUI();};
$('enhance').onclick=e=>{const slot=e.target.dataset.enhance;if(!slot||!town)return;const cost=20*(s.enhance[slot]+1);if(s.materials<cost||s.enhance[slot]>=10)return;s.materials-=cost;s.enhance[slot]++;log(slotName[slot]+' 育成 +'+s.enhance[slot]);persist();renderUI();};
document.addEventListener('visibilitychange',()=>{if(document.hidden){running=false;persist();renderUI();}lastTime=null;});
const canvas=$('battle'),g=canvas.getContext('2d'),colors={physical:'#8cb9ae',fire:'#e6a069',water:'#88c9e4',wind:'#b8cf93',earth:'#c6a16a',light:'#eee0a6',dark:'#bb9ad8'},elName={physical:'無',fire:'火',water:'水',wind:'風',earth:'土',light:'光',dark:'闇'};
function enemy(e,i,now){if(e.hp<=0)return;const x=610+i*88,y=369-i*15,bob=Math.sin(now*2+i)*3,scale=boss?1.3:1;g.save();g.translate(x,y);g.scale(scale,scale);g.fillStyle='#07131c80';g.beginPath();g.ellipse(0,9,44,10,0,0,Math.PI*2);g.fill();g.translate(0,bob);const glow=g.createRadialGradient(-12,-49,2,0,-25,62);glow.addColorStop(0,colors[e.element]);glow.addColorStop(1,'#244653');g.fillStyle=glow;g.beginPath();g.moveTo(-42,0);g.bezierCurveTo(-51,-20,-30,-31,-29,-57);g.bezierCurveTo(-24,-85,-6,-83,0,-98);g.bezierCurveTo(8,-75,28,-63,30,-44);g.bezierCurveTo(36,-26,52,-14,43,0);g.quadraticCurveTo(0,16,-42,0);g.fill();g.fillStyle='#102435';g.beginPath();g.ellipse(-12,-37,5,8,.2,0,7);g.ellipse(13,-37,5,8,-.2,0,7);g.fill();g.fillStyle='#f4f0c6';g.fillRect(-14,-41,3,4);g.fillRect(11,-41,3,4);g.restore();g.fillStyle='#0a1720';g.fillRect(x-35,y-128,70,5);g.fillStyle=colors[e.element];g.fillRect(x-35,y-128,70*e.hp/e.maxHp,5);g.font='12px sans-serif';g.textAlign='center';g.fillStyle='#d6dedb';g.fillText((boss?'守護霊':'精霊')+' · '+elName[e.element],x,y-139);}
function draw(now){g.clearRect(0,0,900,460);const bg=g.createLinearGradient(0,0,0,460);bg.addColorStop(0,'#10202e');bg.addColorStop(1,'#34474a');g.fillStyle=bg;g.fillRect(0,0,900,460);g.fillStyle='#c3d1bc';g.globalAlpha=.16;g.beginPath();g.arc(710,90,39,0,7);g.fill();g.globalAlpha=1;for(let i=0;i<12;i++){g.fillStyle=i%2?'#172e38':'#203742';g.fillRect(i*87+15,110+(i*41)%100,13,255);g.beginPath();g.ellipse(i*87+18,120+(i*41)%100,75,80,0,0,7);g.fill();}g.fillStyle='#29413e';g.fillRect(0,373,900,87);g.strokeStyle='#567064';g.lineWidth=1;for(let i=0;i<28;i++){const x=i*37%900,y=390+i*13%65;g.beginPath();g.moveTo(x,y);g.lineTo(x+9,y-3);g.stroke();}if(forestImage)g.drawImage(forestImage,0,0,900,460);if(!ready)return;
 const a=action,elapsed=a?((gen?totalBase+fightTime:s.seconds)-(a.born??(totalBase+a.time)))/a.duration:1;const clock=gen?totalBase+fightTime:s.seconds;
 g.save();g.translate(5+heroAdvance,14);g.fillStyle='#05111266';g.beginPath();g.ellipse(290,354,60,9,0,0,7);g.fill();g.restore();
 if(supportDraw&&clock-hurtStamp>=0&&clock-hurtStamp<.12){g.save();g.translate(5+heroAdvance,14);supportDraw('hurt',clock-hurtStamp);g.restore();}
 else if(supportDraw&&a?.id==='heal_potion'&&elapsed<1){g.save();g.translate(5+heroAdvance,14);supportDraw('potion',elapsed);g.restore();}
 else if(supportDraw&&running&&heroAdvance<139){g.save();g.translate(5+heroAdvance,14);supportDraw('walk',clock);g.restore();}
 else if(supportDraw&&!a){g.save();g.translate(5+heroAdvance,14);supportDraw(town?townPose:'idle',clock);g.restore();}
 else heroMotion.draw({id:a?.id,progress:elapsed,now:clock,x:5+heroAdvance,y:14,state:town?'idle':'combat'});
 (view?.foes||[]).forEach((e,i)=>enemy(e,i,now));
 const stamp=gen?totalBase+fightTime:s.seconds;elementBursts=elementBursts.filter(e=>stamp-e.born<1.1);for(const e of elementBursts){const age=stamp-e.born;if(age>=0)ElementArt.draw(g,e.element,610+e.target*88,315-e.target*15,age*1000);}floating=floating.filter(e=>stamp-e.born<.65);for(const e of floating){const age=stamp-e.born;if(age<0)continue;const x=e.type==='hurt'?270:610+e.target*88,y=e.type==='hurt'?180:230-e.target*15;g.globalAlpha=Math.max(0,1-age/.65);g.fillStyle=e.type==='hurt'?'#f1b1a0':e.element&&e.element!=='physical'?colors[e.element]:e.crit?'#ffe6a1':'#ffffff';g.font=(e.crit?'bold 25':'bold 20')+'px sans-serif';g.textAlign='center';g.fillText(e.type==='miss'?'MISS':Math.round(e.damage),x,y-age*50);if(e.type==='hit'&&age<.2){g.strokeStyle='#fff2be';g.shadowColor='#efbd68';g.shadowBlur=15;g.lineWidth=2;for(let i=0;i<6;i++){const ang=i*Math.PI/3;g.beginPath();g.moveTo(x+Math.cos(ang)*8,315+Math.sin(ang)*8);g.lineTo(x+Math.cos(ang)*(15+age*110),315+Math.sin(ang)*(15+age*110));g.stroke();}g.shadowBlur=0;}g.globalAlpha=1;}}
function tick(now){try{const dt=lastTime===null?0:Math.min(.1,(now-lastTime)/1000);lastTime=now;if(running&&gen){fightTime+=dt;let guard=0;while(next&&guard++<100){const v=next.done?next.value.view:next.value;if(v.seconds>fightTime+1e-8)break;if(next.done){finish(next.value);break;}accept(v);next=gen.next();}}if(running&&!town){const target=(view?.foes||[]).findIndex(e=>e.hp>0);const desired=target<0?heroAdvance:140+target*88;heroAdvance+=Math.sign(desired-heroAdvance)*Math.min(Math.abs(desired-heroAdvance),1100*dt);}draw(now/1000);if(now-lastPaint>100){renderVitals();lastPaint=now;}}catch(e){running=false;notice('戦闘を停止しました：'+e.message);console.error(e);}requestAnimationFrame(tick);}
renderQueue();p=player();renderUI();
async function loadSceneImage(url){const im=new Image();im.src=url;await im.decode();return im;}
Promise.all([SwordArt.load('../restored/connected-combo.webp'),SwordArt.load('../restored/skill-motion-set.webp'),SwordArt.load('assets/diagonal-slash.webp'),loadSceneImage('assets/forest.webp'),SwordArt.load('assets/support.webp')]).then(([a,b,c,bg,support])=>{combo=SwordArt.combo(g,a);other=SwordArt.other(g,b);heroMotion=HeroMotion.create(g,{combo,other,basic:DiagonalSlash.create(g,c)});forestImage=bg;supportDraw=SwordSupport.create(g,support);ready=true;enterTown();notice(loadWarning||'行動順を整えて、冒険へ。拾った装備は町で装備できます。');}).catch(e=>{notice('素材を読み込めませんでした。ページを再読み込みしてください。');console.error(e);});requestAnimationFrame(tick);
